export const contacts = [
  {
    contact: "8056063139",
    name: "Vishal",
    companyName: "Sociallink",
    place: "NexGen",
  },
  {
    contact: "8489767296",
    name: "Winfred",
    companyName: "NexGen Labs",
    place: "NexGen",
  },

  {
    contact: "8089678967",
    name: "Prabhu",
    companyName: "NexGen Labs",
    place: "NexGen",
  },
  {
    contact: "8249554989",
    name: "Kushal",
    companyName: "NexGen Labs",
    place: "NexGen",
  },
  {
    contact: "7904172010",
    name: "Nexgen meds",
    companyName: "NexGen Labs",
    place: "NexGen",
  },
  {
    contact: "9962581190",
    name: "Karthik",
    place: "NexGen",
    companyName: "NexGen Labs",
  },
  {
    contact: "9790895396",
    name: "Surya",
    companyName: "NexGen Labs",
    place: "NexGen",
  },
  {
    contact: "9790953563",
    name: "Subramani",
    companyName: "NexGen Labs",
    place: "NexGen",
  },
  {
    contact: "9894090408",
    name: "Abdullah",
    place: "AARANI",
    companyName: "SANKAR PHARMA",
  },
  {
    contact: "9994433770",
    name: "Abdullah",
    place: "AMBUR",
    companyName: "SRI MARUTHI PHARMA",
  },
  {
    contact: "9600008608",
    name: "Abdullah",
    place: "AMBUR",
    companyName: "VM PHARMA DISTRIBUTORS",
  },
  {
    contact: "9942121983",
    name: "Vijaykumar",
    place: "ARIYALUR",
    companyName: "INDIAN PHARMA",
  },
  {
    contact: "9655584850",
    name: "Abdullah",
    place: "ARNI ",
    companyName: "S.R.E. HEALTH CARE",
  },
  {
    contact: "9442387892",
    name: "Vijaykumar",
    place: "ATTUR",
    companyName: "DOLLAR PHARMACY",
  },
  {
    contact: "9443077994",
    name: "Vijaykumar",
    place: "ATTUR",
    companyName: "POPULAR DRUG HOSUE",
  },
  {
    contact: "9159770795",
    name: "Vijaykumar",
    place: "ATTUR",
    companyName: "S.P.L PHARMA &MEDICALS",
  },
  {
    contact: "7010212248",
    name: "Vijaykumar",
    place: "ATTUR",
    companyName: "SRI DURGA PHARMA",
  },
  {
    contact: "8124544744",
    name: "undefined",
    place: "vatlagundu",
    companyName: "VIN PHARMA",
  },
  {
    contact: "9884585898",
    name: "Prem",
    place: "CHENNAI",
    companyName: "BHIKSHU PHARMA DISTRIBUTORS",
  },
  {
    contact: "9841065987",
    name: "Prem",
    place: "Chennai",
    companyName: "GANESH PHARMACEUTICALS",
  },
  {
    contact: "9940083206",
    name: "Prem",
    place: "Chennai",
    companyName: "HEALTHZONE PHARMAA",
  },
  {
    contact: "9444137924",
    name: "Prem",
    place: "Chennai",
    companyName: "KUMARAN AGENCIES",
  },
  {
    contact: "9840852528",
    name: "Prem",
    place: "Chennai",
    companyName: "M.M.MEDICOS",
  },
  {
    contact: "9677033549",
    name: "Prem",
    place: "Chennai",
    companyName: "MAS HEALTH CARE",
  },
  {
    contact: "7604927957",
    name: "Prem",
    place: "Chennai",
    companyName: "MED POINT ENTERPRISES",
  },
  {
    contact: "8144533555",
    name: "Prem",
    place: "Chennai",
    companyName: "MEDIX PHARMACEUTICALS",
  },
  {
    contact: "9443030685",
    name: "Prem",
    place: "Chennai",
    companyName: "MOHAN PHARMA",
  },
  {
    contact: "9884242450",
    name: "Prem",
    place: "Chennai",
    companyName: "ORGANICS PHARMACEUTICALS",
  },
  {
    contact: "7904220061",
    name: "Prem",
    place: "Chennai",
    companyName: "OSCAR PHARMACEUTICALS",
  },
  {
    contact: "9551441393",
    name: "Prem",
    place: "Chennai",
    companyName: "SRI MEENAKSHI AGENCY",
  },
  {
    contact: "9884169207",
    name: "Prem",
    place: "Chennai",
    companyName: "SRI NAKODA PHARMACEUTICALS",
  },
  {
    contact: "6381703792",
    name: "Prem",
    place: "Chennai",
    companyName: "SRI THANIGAI PHARMA",
  },
  {
    contact: "9094806135",
    name: "Prem",
    place: "CHENNAI",
    companyName: "SRI THANIGAI PHARMACEUTICALS",
  },
  {
    contact: "9841322235",
    name: "Prem",
    place: "CHENNAI",
    companyName: "SRI TULSI PHARMA DISTRIBUTOR",
  },
  {
    contact: "9840221467",
    name: "Prem",
    place: "Chennai",
    companyName: "SRS ENTERPRISES",
  },
  {
    contact: "9500073183",
    name: "Prem",
    place: "CHENNAI- S.KOLATHUR",
    companyName: "RAMSON PHARMA",
  },
  {
    contact: "9710107659",
    name: "Prem",
    place: "CHENNAI-ADAMBAKKAM",
    companyName: "J.P.PHARMA",
  },
  {
    contact: "9884892145",
    name: "Prem",
    place: "CHENNAI-AMBATTUR",
    companyName: "ESWAR MEDICAL AGENCIES",
  },
  {
    contact: "8610386060",
    name: "Prem",
    place: "CHENNAI-ANNANAGAR",
    companyName: "R.S.VACCINES AND SURGICALS",
  },
  {
    contact: "7010858902",
    name: "Prem",
    place: "CHENNAI-ARUMBAKKAM",
    companyName: "NAVAKAR PHARMA",
  },
  {
    contact: "9962577477",
    name: "Prem",
    place: "CHENNAI-CHETPET",
    companyName: "MS PHARMA AND DISTRIBUTORS",
  },
  {
    contact: "9094202299",
    name: "Prem",
    place: "CHENNAI-CHOOLAI",
    companyName: "R R HEALTH CARE",
  },
  {
    contact: "9080171367",
    name: "Prem",
    place: "CHENNAI-CHROMPET",
    companyName: "S.P PHARMA",
  },
  {
    contact: "6379895556",
    name: "Prem",
    place: "CHENNAI-GUDUVANCHERI",
    companyName: "DX3 AGENCY DRUG & SUGICALS",
  },
  {
    contact: "9841652589",
    name: "Prem",
    place: "CHENNAI-KILAMBAKKAM",
    companyName: "METRO ENTERPRISES",
  },
  {
    contact: "9626108917",
    name: "Prem",
    place: "CHENNAI-KOOVATHUR",
    companyName: "SRI SRINIVASA MEDICALS",
  },
  {
    contact: "9840054896",
    name: "Prem",
    place: "CHENNAI-KOTTAIVAKKAM",
    companyName: "SRI ANNAI PHARMA",
  },
  {
    contact: "9941729727",
    name: "Prem",
    place: "CHENNAI-KOTTIVAKKAM",
    companyName: "KARTHICK PHARMA",
  },
  {
    contact: "9710728313",
    name: "Prem",
    place: "CHENNAI-KOVUR",
    companyName: "MEENAKCHI PHARMACEUTICALS",
  },
  {
    contact: "9884478132",
    name: "Prem",
    place: "CHENNAI-KUNDRATHUR",
    companyName: "JK ENTERPRISES",
  },
  {
    contact: "9789999606",
    name: "Prem",
    place: "CHENNAI-MADIPAKKAM",
    companyName: "JAI TULSI PHARMA",
  },
  {
    contact: "9677033549",
    name: "Prem",
    place: "CHENNAI-MADIPAKKAM",
    companyName: "MAS HEALTHCARE",
  },
  {
    contact: "9840510652",
    name: "Prem",
    place: "CHENNAI-MANGADU",
    companyName: "DHANVANTHRI MEDICAL AGENCIES",
  },
  {
    contact: "9080374577",
    name: "Prem",
    place: "CHENNAI-METTUKUPPAM",
    companyName: "SRI MALAIYAAN PHARMA",
  },
  {
    contact: "9941298491",
    name: "Prem",
    place: "CHENNAI-MMDA",
    companyName: "SRI SA MEDICALS",
  },
  {
    contact: "9884271625",
    name: "Prem",
    place: "CHENNAI-NEMILICHERY",
    companyName: "SRI RAGHAVANDRA DRUGS",
  },
  {
    contact: "9941141600",
    name: "Prem",
    place: "CHENNAI-NYNIAPPA",
    companyName: "BRITISH PHARMA",
  },
  {
    contact: "9884472619",
    name: "Prem",
    place: "CHENNAI-NYNIAPPA",
    companyName: "EMSON PHARMACEUTICALS",
  },
  {
    contact: "9840191274",
    name: "Prem",
    place: "CHENNAI-NYNIAPPA",
    companyName: "VENUS AGENCY",
  },
  {
    contact: "9791666990",
    name: "Prem",
    place: "CHENNAI-PALAVAKKAM",
    companyName: "ABIRAMI MEDICAL AGENCIES",
  },
  {
    contact: "9884030994",
    name: "Prem",
    place: "CHENNAI-PALAVAKKAM",
    companyName: "AMMAN HEALTH CARE",
  },
  {
    contact: "9840312123",
    name: "Prem",
    place: "CHENNAI-PARKTOWN",
    companyName: "GYAN PHARMA",
  },
  {
    contact: "9840291001",
    name: "Prem",
    place: "CHENNAI-PATTABIRAM",
    companyName: "DADA GANESH PHARMACEUTICALS",
  },
  {
    contact: "9551285557",
    name: "Prem",
    place: "CHENNAI-PATTABIRAM",
    companyName: "TIRUMALA PHARMA DISTRIBUTORS",
  },
  {
    contact: "9841721868",
    name: "Prem",
    place: "CHENNAI-POONNAMALLI",
    companyName: "SRI VAISHIYA PHARMA",
  },
  {
    contact: "8939997717",
    name: "Prem",
    place: "CHENNAI-PURASAIWALKAM",
    companyName: "JL CITY PHARMA INDIA LTD.",
  },
  {
    contact: "9840450564",
    name: "Prem",
    place: "CHENNAI-PUZTHIVAKKAM",
    companyName: "SRI VIJAY GANAPATHY ENTERPRISES",
  },
  {
    contact: "9445358909",
    name: "Prem",
    place: "CHENNAI-REDHILLS",
    companyName: "SRI VARI MEDICAL DISTRIBUTORS",
  },
  {
    contact: "9841582364",
    name: "Prem",
    place: "CHENNAI-TAMBARAM",
    companyName: "NEWGOLD ENTERPRISES",
  },
  {
    contact: "9840604854",
    name: "Prem",
    place: "CHENNAI-TAMBARAM",
    companyName: "SHRI RAM MEDICAL AGENCIES",
  },
  {
    contact: "9841806770",
    name: "Prem",
    place: "CHENNAI-THIRUMULLAIVOYAL",
    companyName: "GOOD PHARMACEUTICALS",
  },
  {
    contact: "8248817911",
    name: "Prem",
    place: "CHENNAI-THIRUMULLAIVOYAL",
    companyName: "LAKSHMI PHARMA &SURGICAL",
  },
  {
    contact: "9841259635",
    name: "Prem",
    place: "CHENNAI-THIRUNINRAVUR",
    companyName: "EMMANUEL PHARMA &SUGICALS",
  },
  {
    contact: "9942448743",
    name: "Prem",
    place: "CHENNAI-TIRUVALLUR",
    companyName: "ANAND MEDICAL AGENCY",
  },
  {
    contact: "7639578630",
    name: "Prem",
    place: "CHENNAI-TIRUVALLUR",
    companyName: "SARAVANAN PHARMA",
  },
  {
    contact: "7401683114",
    name: "Prem",
    place: "CHENNAI-TONDIARPET",
    companyName: "PUSHPUM TRADERS ",
  },
  {
    contact: "9940091419",
    name: "Prem",
    place: "CHENNAI-VALASARAVAKKAM",
    companyName: "AMMAN DRUGS",
  },
  {
    contact: "9551650275",
    name: "Prem",
    place: "CHENNAI-VANAGARAM",
    companyName: "KARPAGAM MEDICAL AGENCIES",
  },
  {
    contact: "9551441393",
    name: "Prem",
    place: "CHENNAI-VANDALUR",
    companyName: "SRI MEENAKCHI PHARMA",
  },
  {
    contact: "9940567788",
    name: "Prem",
    place: "CHENNAI-VILLIVAKKAM",
    companyName: "HARSHA ENTERPRISES",
  },
  {
    contact: "7402623083",
    name: "Vijaykumar",
    place: "CHIDAMBARAM",
    companyName: "BALA SARASWATHI SURGICALS AND PHARMACEUT",
  },
  {
    contact: "9442403699",
    name: "Vijaykumar",
    place: "CHIDAMBARAM",
    companyName: "LAKSHMI PHARMA & SURGICALS",
  },
  {
    contact: "9894860723",
    name: "Vijaykumar",
    place: "CHIDAMBARAM",
    companyName: "N T R AGENCIES",
  },
  {
    contact: "9894860723",
    name: "Vijaykumar",
    place: "CHIDAMBARAM",
    companyName: "NTR AGENCIES",
  },
  {
    contact: "9442566474",
    name: "Vijaykumar",
    place: "CHIDAMBARAM",
    companyName: "SAAI GIRI AGENCIES",
  },
  {
    contact: "9488521474",
    name: "Vijaykumar",
    place: "CHIDAMBARAM",
    companyName: "SRI SAAI GIRI AGENCIES",
  },
  {
    contact: "9789678456",
    name: "Venkat",
    place: "CHINAMANNUR",
    companyName: "GANAPATHY MEDICAL AGENCY",
  },
  {
    contact: "8973744595",
    name: "Venkat",
    place: "CHINAMANNUR",
    companyName: "UDAYAM PHARMA",
  },
  {
    contact: "9865073829",
    name: "Venkat",
    place: "CHINAMANNUR",
    companyName: "VASANTHAM PHARMACETICALS",
  },
  {
    contact: "8667070573",
    name: "Vijaykumar",
    place: "CHINNASALEM ",
    companyName: "JEEVA PHARMA",
  },
  {
    contact: "9842220985",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "AKASH PHARMA",
  },
  {
    contact: "9500827485",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "ALAMU PHARMA",
  },
  {
    contact: "8825818180",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "ALPHA PHARMA",
  },
  {
    contact: "9443722353",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "AMMAN MEDICAL AGENCIES",
  },
  {
    contact: "9865999956",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "ANNAMALAI AGENCIES",
  },
  {
    contact: "9840322379",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "ARJUN PHARMA",
  },
  {
    contact: "9597833798",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "BAKIYALAKSHMI AGENCIES",
  },
  {
    contact: "9600972208",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "DHARSHAN PHARMA",
  },
  {
    contact: "8220661155",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "GOKUL AGENCIES",
  },
  {
    contact: "9600668939",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "JEYANTHI PHARMAA",
  },
  {
    contact: "9789514996",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "K M PHARMA",
  },
  {
    contact: "9894553122",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "MED FIRST",
  },
  {
    contact: "9443209595",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "MEDISTAR PHARMA",
  },
  {
    contact: "9597808075",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "MEDWIN PHARMA",
  },
  {
    contact: "9842164678",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "NAGAPPA AGENCIES",
  },
  {
    contact: "9080007090",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "OSCAR PHARMA",
  },
  {
    contact: "9489139555",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "RAMVEL PHARMA",
  },
  {
    contact: "9842244562",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "RATHNA PHARMA DISTRIBUTORS",
  },
  {
    contact: "9842280985",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "SAKTHI AGENCIES",
  },
  {
    contact: "9597749299",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "SENTHIL AGENIECS",
  },
  {
    contact: "9865999956",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "SHRI ANNAAMALAI AGENCIES",
  },
  {
    contact: "9994161123",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "SIVAGAMI PHARMA",
  },
  {
    contact: "9942209222",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "SRE SAIRAM MEDCIAL AGENCIES",
  },
  {
    contact: "9842011940",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "SRI ANUSHA AGENCIES",
  },
  {
    contact: "9994500338",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "SRI MEENAKCHI PHARMA",
  },
  {
    contact: "9842234025",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "SRI SASTHA PHARMA",
  },
  {
    contact: "9487873191",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "SRI VALLI PHARMA",
  },
  {
    contact: "9842223121",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "SRI VIGENSHWAR PHARMA",
  },
  {
    contact: "9842223121",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "SRI VIGNESHWAR PHARMACEUTICAL DISTRIBUTOR",
  },
  {
    contact: "9965534652",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "SRI VINAYAGA PHARMA",
  },
  {
    contact: "9865761710",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "SUCCESS PHARMA",
  },
  {
    contact: "9486442889",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "UDHAYAM AGENCIES",
  },
  {
    contact: "9865866510",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "VENUS PHARMA",
  },
  {
    contact: "9965534652",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "VINAYAKA PHARMA",
  },
  {
    contact: "6379697844",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "WELNESS PHARMA",
  },
  {
    contact: "9843005004",
    name: "Abdullah",
    place: "COIMBATORE",
    companyName: "YUNG PHARMA",
  },
  {
    contact: "9486022884",
    name: "undefined",
    place: "COONOOR",
    companyName: "COONOOR DRUG HOUSE",
  },
  {
    contact: "9444497764",
    name: "Vijaykumar",
    place: "CUDDALORE",
    companyName: "BAIRAVAA AGENCIES",
  },
  {
    contact: "9489543233",
    name: "Vijaykumar",
    place: "CUDDALORE",
    companyName: "GANAPATHI AGENCIES",
  },
  {
    contact: "6381338513",
    name: "Vijaykumar",
    place: "CUDDALORE",
    companyName: "JAIGANESH PHARMA",
  },
  {
    contact: "8438998646",
    name: "Vijaykumar",
    place: "CUDDALORE",
    companyName: "KARUNYA AGENCIES",
  },
  {
    contact: "9443537592",
    name: "Vijaykumar",
    place: "CUDDALORE",
    companyName: "MAHALAKSHMI AGENCIES",
  },
  {
    contact: "8220192606",
    name: "Vijaykumar",
    place: "CUDDALORE",
    companyName: "SREE ANDAL AGENCIES",
  },
  {
    contact: "9043792382",
    name: "Vijaykumar",
    place: "CUDDALORE",
    companyName: "SRI VIGNESH PHARMA",
  },
  {
    contact: "9443891652",
    name: "Vijaykumar",
    place: "CUDDALORE",
    companyName: "VASANTHA PHARMA",
  },
  {
    contact: "8526849771",
    name: "Vijaykumar",
    place: "CUDDALORE",
    companyName: "VEL PHARMA",
  },
  {
    contact: "9994819766",
    name: "Venkat",
    place: "CUMBAM",
    companyName: "APM MEDICAL AGENCIES",
  },
  {
    contact: "9080503460",
    name: "Venkat",
    place: "CUMBAM",
    companyName: "PRIYAM PHARMA",
  },
  {
    contact: "9842582197",
    name: "Venkat",
    place: "CUMBAM",
    companyName: "TAJ PHARMA",
  },
  {
    contact: "6381428813",
    name: "Venkat",
    place: "CUMBUM",
    companyName: "NAVEEN PHARMA",
  },
  {
    contact: "9443476452",
    name: "Venkat",
    place: "CUMBUM",
    companyName: "VAIGAI PHARMA",
  },
  {
    contact: "9842496834",
    name: "Venkat",
    place: "DEVAKOTTAI",
    companyName: "MUTHU MEDICAL AGENCIES",
  },
  {
    contact: "9786088291",
    name: "Venkat",
    place: "DEVAKOTTAI",
    companyName: "SAMY MEDICAL AGENCY",
  },
  {
    contact: "9944317112",
    name: "Abdullah",
    place: "DHARMAPURI",
    companyName: "DEVA MEDICAL AGENCY",
  },
  {
    contact: "9865246664",
    name: "Abdullah",
    place: "DHARMAPURI",
    companyName: "GLOBAL PHARMA DISTRIBUTORS",
  },
  {
    contact: "7373668833",
    name: "Abdullah",
    place: "DHARMAPURI",
    companyName: "KANI PHARMA&SURGICALS",
  },
  {
    contact: "6381379319",
    name: "Abdullah",
    place: "DHARMAPURI",
    companyName: "KAVIYA PHARMA",
  },
  {
    contact: "9585238238",
    name: "Abdullah",
    place: "DHARMAPURI",
    companyName: "SHREE VIJAY PHARMA",
  },
  {
    contact: "9715583888",
    name: "Abdullah",
    place: "DHARMAPURI",
    companyName: "SHRI PHARMA",
  },
  {
    contact: "9688104397",
    name: "Abdullah",
    place: "DHARMAPURI",
    companyName: "SIVA SAKTHI PHARMA",
  },
  {
    contact: "9486351081",
    name: "Abdullah",
    place: "DHARMAPURI",
    companyName: "SOWBAIYA AGENCIES",
  },
  {
    contact: "9443963438",
    name: "Abdullah",
    place: "DHARMAPURI",
    companyName: "SRI BALAJI PHARMA SURGICALS",
  },
  {
    contact: "9500245930",
    name: "Abdullah",
    place: "DHARMAPURI",
    companyName: "SRI VENKATESHWARA PHARMA",
  },
  {
    contact: "9445230075",
    name: "Abdullah",
    place: "DHARMAPURI",
    companyName: "SRI VETRI PHARMA",
  },
  {
    contact: "9597943678",
    name: "Venkat",
    place: "DINDIGUL",
    companyName: "AT PHARMA",
  },
  {
    contact: "9150321006",
    name: "Venkat",
    place: "DINDIGUL",
    companyName: "PACKIALAXMI PHARMA",
  },
  {
    contact: "9080548278",
    name: "Venkat",
    place: "DINDIGUL",
    companyName: "RAJA PHARMA AGENCY",
  },
  {
    contact: "9150244333",
    name: "Venkat",
    place: "DINDUGUL",
    companyName: "INDIAN PHARMA DISTRIBUTOR",
  },
  {
    contact: "9150905246",
    name: "Venkat",
    place: "DINDUGUL",
    companyName: "LEADER PHARMA",
  },
  {
    contact: "8012073917",
    name: "Venkat",
    place: "DINDUGUL",
    companyName: "RAJA MEDICAL CORPORATION",
  },
  {
    contact: "9952455701",
    name: "Venkat",
    place: "DINDUGUL",
    companyName: "SAI VELAN PHARMA",
  },
  {
    contact: "9894111007",
    name: "Venkat",
    place: "DINDUGUL",
    companyName: "WIN PHARMA",
  },
  {
    contact: "9282174222",
    name: "Abdullah",
    place: "ERODE",
    companyName: "ALL POWER SYSTEM",
  },
  {
    contact: "9965619539",
    name: "Abdullah",
    place: "ERODE",
    companyName: "DHANVANTHIRI PHARMACEUTICALS",
  },
  {
    contact: "9840585346",
    name: "Abdullah",
    place: "ERODE",
    companyName: "DR. PHARMA",
  },
  {
    contact: "9629093150",
    name: "Abdullah",
    place: "ERODE",
    companyName: "ERODE PHARMA",
  },
  {
    contact: "8428090777",
    name: "Abdullah",
    place: "ERODE",
    companyName: "ERODE SURGICALS",
  },
  {
    contact: "8248795370",
    name: "Abdullah",
    place: "ERODE",
    companyName: "GAJALAKSHMI PHARMA",
  },
  {
    contact: "9442253254",
    name: "Abdullah",
    place: "ERODE",
    companyName: "HI-TECH DRUGS",
  },
  {
    contact: "9500580997",
    name: "Abdullah",
    place: "ERODE",
    companyName: "HUMAN CARE PHARMACETICALS",
  },
  {
    contact: "9894665500",
    name: "Abdullah",
    place: "ERODE",
    companyName: "IDEAL SURGICALS",
  },
  {
    contact: "9994822119",
    name: "Abdullah",
    place: "ERODE",
    companyName: "JEEVAN PHRMACY",
  },
  {
    contact: "9994437537",
    name: "Abdullah",
    place: "ERODE",
    companyName: "KRISHNA PHARMA",
  },
  {
    contact: "9965828777",
    name: "Abdullah",
    place: "ERODE",
    companyName: "LIFE CARE PHARMACETICALS",
  },
  {
    contact: "9360093973",
    name: "Abdullah",
    place: "ERODE",
    companyName: "M.R PHARMA",
  },
  {
    contact: "9994020111",
    name: "Abdullah",
    place: "ERODE",
    companyName: "MYURA SURGICAL PHARMA",
  },
  {
    contact: "9994020111",
    name: "Abdullah",
    place: "ERODE",
    companyName: "MYURA SURGICAL PHARMA",
  },
  {
    contact: "9944614100",
    name: "Abdullah",
    place: "ERODE",
    companyName: "NANDHI PHARMA",
  },
  {
    contact: "9842797669",
    name: "Abdullah",
    place: "ERODE",
    companyName: "PHARMA TRADERS ",
  },
  {
    contact: "9994959434",
    name: "Abdullah",
    place: "ERODE",
    companyName: "PREETHA MEDICAL AGENCY",
  },
  {
    contact: "9994950994",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SAKTHI PHARMA",
  },
  {
    contact: "9500946644",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SHALIMAR DISTRIBUTORS ",
  },
  {
    contact: "9994611226",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SHRI AMBIGAI PHARMA & SURGICAL",
  },
  {
    contact: "9789456388",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SKG PHARMA",
  },
  {
    contact: "9994553777",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SRE AMMAN PHARMA  AGENCY",
  },
  {
    contact: "9994964333",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SRE SARAVANA MEDICAL AGENCIES",
  },
  {
    contact: "9994914383",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SRE SIVAM PHARMA",
  },
  {
    contact: "9994553777",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SREE AMMAN PHARMA AGENCY",
  },
  {
    contact: "9994951516",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SREE BALAJI SUGICALS",
  },
  {
    contact: "9865657314",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SREE MURUGAN PHARMACY",
  },
  {
    contact: "9842032918",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SREE SARASWATHI MEDICAL AGENCIES",
  },
  {
    contact: "9994967817",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SREE SASTHA MEDICAL AGECIES",
  },
  {
    contact: "9865376636",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SRI AMMAN MEDICAL AGRNCIES",
  },
  {
    contact: "9976853777",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SRI AMMAN PHARMACETICALS ",
  },
  {
    contact: "9965129267",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SRI HINDUSTAN MEDICAL AGENCIES",
  },
  {
    contact: "7010748260",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SRI KRISHNA PHARMA",
  },
  {
    contact: "6380773430",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SRI RATHNA PHARMA",
  },
  {
    contact: "9486656660",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SRI SUN PHARMA",
  },
  {
    contact: "9994554555",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SRI VIGNESH MEDICAL AGENCIS",
  },
  {
    contact: "9842319735",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SRI VINAYAGA PHARMA",
  },
  {
    contact: "9842032918",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SRIE SARASWATHI MEDICAL AGENCIES",
  },
  {
    contact: "9443701983",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SUMANGALI PHARMACETICALS",
  },
  {
    contact: "9894050609",
    name: "Abdullah",
    place: "ERODE",
    companyName: "SURABHI AGENCIES",
  },
  {
    contact: "undefined",
    name: "Abdullah",
    place: "ERODE",
    companyName: "TAMILNADU PHARMA",
  },
  {
    contact: "9500655572",
    name: "Abdullah",
    place: "ERODE",
    companyName: "THANGAM DRUGS",
  },
  {
    contact: "9842866873",
    name: "Abdullah",
    place: "ERODE",
    companyName: "VENUS AGENCY",
  },
  {
    contact: "9443054383",
    name: "Abdullah",
    place: "ERODE",
    companyName: "VIJAI PHARMA & SURGICALS",
  },
  {
    contact: "9443054383",
    name: "Abdullah",
    place: "ERODE",
    companyName: "VIJAY PHARMA AND SURGICALS",
  },
  {
    contact: "9159153939",
    name: "Abdullah",
    place: "ERODE",
    companyName: "WELL CARE PHARMA",
  },
  {
    contact: "9488950073",
    name: "Vijaykumar",
    place: "GINGEE",
    companyName: "GUHAN PHARMA AND SURGICALS",
  },
  {
    contact: "9842405690",
    name: "Vijaykumar",
    place: "GINGEE",
    companyName: "MEENAKSHI DRUG HOUSE",
  },
  {
    contact: "9842722812",
    name: "Abdullah",
    place: "GOBICHETTIPALAYAM",
    companyName: "ABHIRAMI MEDICAL SUPPLIERS",
  },
  {
    contact: "9655130278",
    name: "Abdullah",
    place: "GUDIYATAM",
    companyName: "SRI VARI PHARMA",
  },
  {
    contact: "9443442057",
    name: "Abdullah",
    place: "HARUR",
    companyName: "SRI RAM PHARMA",
  },
  {
    contact: "7975183471",
    name: "Abdullah",
    place: "HOSUR",
    companyName: "BHAVESH DISTRIBUTOR",
  },
  {
    contact: "7010403639",
    name: "Abdullah",
    place: "HOSUR",
    companyName: "HOSUR PHARMA DISTRIBUTIORS",
  },
  {
    contact: "9443618545",
    name: "Abdullah",
    place: "HOSUR",
    companyName: "NEW SKY PHARMA",
  },
  {
    contact: "9443082960",
    name: "Abdullah",
    place: "HOSUR",
    companyName: "PRABHA DRUG HOUSE",
  },
  {
    contact: "9443345113",
    name: "Abdullah",
    place: "HOSUR",
    companyName: "RAJ PHARMA",
  },
  {
    contact: "9600745085",
    name: "Abdullah",
    place: "HOSUR",
    companyName: "RAJ SURGICALS ",
  },
  {
    contact: "9443542360",
    name: "Abdullah",
    place: "HOSUR",
    companyName: "RAJESHWAR PHARMA",
  },
  {
    contact: "undefined",
    name: "Abdullah",
    place: "HOSUR",
    companyName: "RAM PHARMA",
  },
  {
    contact: "9790443512",
    name: "Abdullah",
    place: "HOSUR",
    companyName: "SAI LAKSHMI MEDICALS",
  },
  {
    contact: "8144603883",
    name: "Vijaykumar",
    place: "JEYANKONDAN",
    companyName: "JAI MARUTHI PHARMA",
  },
  {
    contact: "9443449733",
    name: "Venkat",
    place: "KALIAKAVIAL",
    companyName: "TRINITY MEDICAL AGENCIES",
  },
  {
    contact: "9047087036",
    name: "Vijaykumar",
    place: "KALLAKURICHI",
    companyName: "SRI AKSHAYA AGENCIES",
  },
  {
    contact: "9786479608",
    name: "Vijaykumar",
    place: "KALLAKURICHI",
    companyName: "SRI SURIYA AGENCIES",
  },
  {
    contact: "7418383210",
    name: "Prem",
    place: "KANCHEEPURAM",
    companyName: "AMITY PHARMA",
  },
  {
    contact: "8148544453",
    name: "Prem",
    place: "KANCHEEPURAM",
    companyName: "LAKSHMI PHARMA",
  },
  {
    contact: "6381835903",
    name: "Prem",
    place: "KANCHIPURAM",
    companyName: "AMITY PHARMA",
  },
  {
    contact: "9025718068",
    name: "Prem",
    place: "KANCHIPURAM",
    companyName: "DHARSHAN PHARMA",
  },
  {
    contact: "9445313150",
    name: "Prem",
    place: "KANCHIPURAM",
    companyName: "G.R.AGENCIES",
  },
  {
    contact: "9003887345",
    name: "Prem",
    place: "KANCHIPURAM",
    companyName: "LAKSHMI PHARMA",
  },
  {
    contact: "9994546590",
    name: "Prem",
    place: "KANCHIPURAM",
    companyName: "MURALI MOTHI PHARMA",
  },
  {
    contact: "9444693573",
    name: "Prem",
    place: "KANCHIPURAM",
    companyName: "SRI RAM PHARMA",
  },
  {
    contact: "9443851606",
    name: "Venkat",
    place: "KARAIKUDI",
    companyName: "CITY DRUDS & SURGICAL",
  },
  {
    contact: "9941334930",
    name: "Venkat",
    place: "KARAIKUDI",
    companyName: "DHEIVA MEDICAL AGENCY",
  },
  {
    contact: "9487212639",
    name: "Venkat",
    place: "KARAIKUDI",
    companyName: "MURUGAN MEDICAL AGENCY",
  },
  {
    contact: "8667007971",
    name: "Venkat",
    place: "KARAIKUDI",
    companyName: "NEW LIFE PHARMA",
  },
  {
    contact: "7469976997",
    name: "Venkat",
    place: "KARAIKUDI",
    companyName: "SRI RAJESHWAR MEDICAL",
  },
  {
    contact: "9787730608",
    name: "Venkat",
    place: "KARAIKUDI",
    companyName: "TAMILNADU MEDICAL AGENCIES",
  },
  {
    contact: "9842473631",
    name: "Venkat",
    place: "KARAIKUDI",
    companyName: "THEIVA MEDICAL AGENCIES",
  },
  {
    contact: "9943725151",
    name: "Venkat",
    place: "KARAIKUDI",
    companyName: "THIYAGARAJA TRADER",
  },
  {
    contact: "9865131111",
    name: "Venkat",
    place: "KARAIKUDI",
    companyName: "VINAYAGA MEDICAL AGENCY",
  },
  {
    contact: "9688188666",
    name: "Abdullah",
    place: "KARUR",
    companyName: "ARUL ENTERPRISES",
  },
  {
    contact: "9994066377",
    name: "Abdullah",
    place: "KARUR",
    companyName: "DHEERAN PHARMA",
  },
  {
    contact: "9944030388",
    name: "Abdullah",
    place: "KARUR",
    companyName: "HI TECH PHARMA",
  },
  {
    contact: "9025287450",
    name: "Abdullah",
    place: "KARUR",
    companyName: "LUCKY PHARMA",
  },
  {
    contact: "9842459761",
    name: "Abdullah",
    place: "KARUR",
    companyName: "MAHARANI PHARMA",
  },
  {
    contact: "9677840852",
    name: "Abdullah",
    place: "KARUR",
    companyName: "SENTHIL ANDAVAR AGENCY",
  },
  {
    contact: "9585366877",
    name: "Abdullah",
    place: "KARUR",
    companyName: "SRI MURUGAN PHARMA",
  },
  {
    contact: "9994427691",
    name: "Venkat",
    place: "KOVILPATTI",
    companyName: "J S MEDICAL AGENCY",
  },
  {
    contact: "8903548379",
    name: "Venkat",
    place: "KOVILPATTI",
    companyName: "SRI PARVATHI PHARMA",
  },
  {
    contact: "9443512566",
    name: "Abdullah",
    place: "KRISHNAGIRI",
    companyName: "HARINI AGENCY",
  },
  {
    contact: "9008829997",
    name: "Abdullah",
    place: "KRISHNAGIRI",
    companyName: "PRAKASH PHARMA",
  },
  {
    contact: "7373779119",
    name: "Abdullah",
    place: "KRISHNAGIRI",
    companyName: "SAI VENKATESH AGENCY",
  },
  {
    contact: "9944992294",
    name: "Abdullah",
    place: "KRISHNAGIRI",
    companyName: "SRI RANI PHARMA",
  },
  {
    contact: "9488431303",
    name: "Abdullah",
    place: "KRISHNAGIRI",
    companyName: "SRI SUBALAKSHMI MEDICALS",
  },
  {
    contact: "9043816685",
    name: "Abdullah",
    place: "KRISHNAGIRI",
    companyName: "SRI VENKATESHWARA PHARMA",
  },
  {
    contact: "9942222992",
    name: "Abdullah",
    place: "KRISHNAGIRI",
    companyName: "SRINIVASA AGENCY",
  },
  {
    contact: "9842784028",
    name: "Abdullah",
    place: "KRISHNAGIRI",
    companyName: "VENUS MEDICAL AGENCY",
  },
  {
    contact: "9443513921",
    name: "Abdullah",
    place: "KRISHNAGIRI",
    companyName: "YASOTHA PHARMACEUTICALS",
  },
  {
    contact: "7708788865",
    name: "Vijaykumar",
    place: "KUMBAKONAM",
    companyName: "DELTA PHARMA",
  },
  {
    contact: "9443402903",
    name: "Vijaykumar",
    place: "KUMBAKONAM",
    companyName: "GOLDEN PHARMA",
  },
  {
    contact: "9443394927",
    name: "Vijaykumar",
    place: "Kumbakonam",
    companyName: "PHARMA TRADERS & MARKETING",
  },
  {
    contact: "9443564483",
    name: "Vijaykumar",
    place: "KUMBAKONAM",
    companyName: "SAHARA PHARMA SURGICALS",
  },
  {
    contact: "9952402352",
    name: "Vijaykumar",
    place: "KUMBAKONAM",
    companyName: "SAIRAM PHARMA AGENCIES",
  },
  {
    contact: "7598212956",
    name: "Vijaykumar",
    place: "KUMBAKONAM",
    companyName: "SHREE MUTHIAH MEDICAL AGENCIES",
  },
  {
    contact: "9360220852",
    name: "Vijaykumar",
    place: "Kumbakonam",
    companyName: "SPECIALTY HEALTHCARE",
  },
  {
    contact: "9443650683",
    name: "Vijaykumar",
    place: "KUMBAKONAM",
    companyName: "SRI RAM PHARMA",
  },
  {
    contact: "9894536452",
    name: "Vijaykumar",
    place: "Kumbakonam",
    companyName: "SRI RAM PHARMA",
  },
  {
    contact: "9952402352",
    name: "Vijaykumar",
    place: "KUMBAKONAM",
    companyName: "SRI SAI RAM PHARMA",
  },
  {
    contact: "9952402352",
    name: "Vijaykumar",
    place: "Kumbakonam",
    companyName: "SRI SAIRAM PHARMA DISTRIBUTORS",
  },
  {
    contact: "9362674934",
    name: "Vijaykumar",
    place: "KUMBAKONAM",
    companyName: "SRI SAMI PHARMA",
  },
  {
    contact: "9443488560",
    name: "Vijaykumar",
    place: "KUMBAKONAM",
    companyName: "VASANTHA AGENCIES",
  },
  {
    contact: "7093907762",
    name: "Abdullah",
    place: "KUPPAM",
    companyName: "SRINIVASA AGENCY",
  },
  {
    contact: "9150351693",
    name: "Venkat",
    place: "MADURAI",
    companyName: "A R P PHARMA",
  },
  {
    contact: "7598361229",
    name: "Venkat",
    place: "MADURAI",
    companyName: "ABS FIRM",
  },
  {
    contact: "9344720864",
    name: "Venkat",
    place: "MADURAI",
    companyName: "AISHWARYA PHARMA",
  },
  {
    contact: "9344520001",
    name: "Venkat",
    place: "MADURAI",
    companyName: "ALLAINCE LIFE SCIENCE",
  },
  {
    contact: "9443471063",
    name: "Venkat",
    place: "MADURAI",
    companyName: "AMPA SHRI PHARMA",
  },
  {
    contact: "9750254757",
    name: "Venkat",
    place: "MADURAI",
    companyName: "ANITHA  MEDICAL AGENCIES",
  },
  {
    contact: "9994977323",
    name: "Venkat",
    place: "MADURAI",
    companyName: "APOLLO PHARMA",
  },
  {
    contact: "9750351725",
    name: "Venkat",
    place: "MADURAI",
    companyName: "ARP PHARMA",
  },
  {
    contact: "9600075374",
    name: "Venkat",
    place: "MADURAI",
    companyName: "ASVISH PHARMA AGENCIES",
  },
  {
    contact: "9345294252",
    name: "Venkat",
    place: "MADURAI",
    companyName: "AZAGAR DISTRIBUTORS",
  },
  {
    contact: "9842593114",
    name: "Venkat",
    place: "MADURAI",
    companyName: "DEVADHARSHINI",
  },
  {
    contact: "9944777888",
    name: "Venkat",
    place: "MADURAI",
    companyName: "DR.FAZIL",
  },
  {
    contact: "7373018880",
    name: "Venkat",
    place: "MADURAI",
    companyName: "GALAXY HEALTH CARE",
  },
  {
    contact: "9655977556",
    name: "Venkat",
    place: "MADURAI",
    companyName: "GEE G MEDI SYSTEM",
  },
  {
    contact: "9952414272",
    name: "Venkat",
    place: "MADURAI",
    companyName: "GOOD LIFE PHARMA",
  },
  {
    contact: "9790120697",
    name: "Venkat",
    place: "MADURAI",
    companyName: "HEMA PHARMA",
  },
  {
    contact: "9840669500",
    name: "Venkat",
    place: "MADURAI",
    companyName: "IMAGE BIOMED",
  },
  {
    contact: "9344720864",
    name: "Venkat",
    place: "MADURAI",
    companyName: "ISHWARYA PHARMA",
  },
  {
    contact: "9842121262",
    name: "Venkat",
    place: "MADURAI",
    companyName: "JAYARAMAN PHARMA",
  },
  {
    contact: "7010376776",
    name: "Venkat",
    place: "MADURAI",
    companyName: "JEGANATH PHARMA",
  },
  {
    contact: "9787360087",
    name: "Venkat",
    place: "MADURAI",
    companyName: "K S P PHARMA",
  },
  {
    contact: "7708432680",
    name: "Venkat",
    place: "MADURAI",
    companyName: "KARTHICK PHARMA",
  },
  {
    contact: "9025047147",
    name: "Venkat",
    place: "MADURAI",
    companyName: "LAKSHMI PHARMA",
  },
  {
    contact: "9994447037",
    name: "Venkat",
    place: "MADURAI",
    companyName: "LEKSHNA PHARMA",
  },
  {
    contact: "9894346284",
    name: "Venkat",
    place: "MADURAI",
    companyName: "LK PHARMA",
  },
  {
    contact: "9943264647",
    name: "Venkat",
    place: "MADURAI",
    companyName: "MADURAVALLI PHARMA",
  },
  {
    contact: "9345960679",
    name: "Venkat",
    place: "MADURAI",
    companyName: "MG PHARMA",
  },
  {
    contact: "9842156511",
    name: "Venkat",
    place: "MADURAI",
    companyName: "NATIONAL PHARMA",
  },
  {
    contact: "9842154401",
    name: "Venkat",
    place: "MADURAI",
    companyName: "NEWSUN PHARMA AGENCY",
  },
  {
    contact: "9940762804",
    name: "Venkat",
    place: "MADURAI",
    companyName: "PRIYA PHARMA",
  },
  {
    contact: "9585383339",
    name: "Venkat",
    place: "MADURAI",
    companyName: "PSD PHARMA",
  },
  {
    contact: "9789497460",
    name: "Venkat",
    place: "MADURAI",
    companyName: "PUNNIYA PHARMA",
  },
  {
    contact: "9944666788",
    name: "Venkat",
    place: "MADURAI",
    companyName: "PUSHPA PHARMA",
  },
  {
    contact: "9443375163",
    name: "Venkat",
    place: "MADURAI",
    companyName: "RAJ PHARMACEUTICALS",
  },
  {
    contact: "9843163387",
    name: "Venkat",
    place: "MADURAI",
    companyName: "RAJAMANI ENTERPRISES",
  },
  {
    contact: "9025599760",
    name: "Venkat",
    place: "MADURAI",
    companyName: "RJL ANNAI PHARMA",
  },
  {
    contact: "9486555065",
    name: "Venkat",
    place: "MADURAI",
    companyName: "S P M MEDICAL MART",
  },
  {
    contact: "9842164873",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SABHARISH PHARMA",
  },
  {
    contact: "9345208004",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SAHAM AGENCY",
  },
  {
    contact: "9655033017",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SHRI SWAMY MEDICAL AGENCY",
  },
  {
    contact: "9442882302",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SREE SINDHU ENTERPRISES",
  },
  {
    contact: "9443867932",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SRI AMMAN PHARMACY",
  },
  {
    contact: "9655726009",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SRI DEVI PHARMACETICALS",
  },
  {
    contact: "9842121262",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SRI JEYARAMAN PHARMACEUTICALS",
  },
  {
    contact: "9843424699",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SRI KANNATHAL PHARMA",
  },
  {
    contact: "8870456920",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SRI LAKSHMI AGENCIES",
  },
  {
    contact: "9443262738",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SRI MAHALAKSHMI PHARMA",
  },
  {
    contact: "8754205599",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SRI NALLU PHARMA",
  },
  {
    contact: "9043742039",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SRI RAGAVENDRA AGENCIES",
  },
  {
    contact: "9443484107",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SRI RAM PHARMA",
  },
  {
    contact: "9585530055",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SRI RIVETHAA PHARMA",
  },
  {
    contact: "9789782025",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SRI SENTHIL ANDAVAR MEDICAL AGENCIES",
  },
  {
    contact: "9943766337",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SRI SHENBAGA VINAYAGAR AGENCIES",
  },
  {
    contact: "9443485027",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SRI SIVAKUMAR PHARMA",
  },
  {
    contact: "9095019333",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SRI VenkatESWARA ENTERPRISES",
  },
  {
    contact: "9842323676",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SRI VETRI PHARMA",
  },
  {
    contact: "8825482481",
    name: "Venkat",
    place: "MADURAI",
    companyName: "STAR PHARMA",
  },
  {
    contact: "9842102526",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SUN MEDICAL & SURGICALS",
  },
  {
    contact: "9894880366",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SURYA ENTERPRISES",
  },
  {
    contact: "8754954406",
    name: "Venkat",
    place: "MADURAI",
    companyName: "SWASTIK PHARMA",
  },
  {
    contact: "9698988080",
    name: "Venkat",
    place: "MADURAI",
    companyName: "UMAYAL AEGNCIES",
  },
  {
    contact: "9952734311",
    name: "Venkat",
    place: "MADURAI",
    companyName: "VANI ENTERPRISES",
  },
  {
    contact: "9514969988",
    name: "Venkat",
    place: "MADURAI",
    companyName: "VE. S PHARMA",
  },
  {
    contact: "9443279424",
    name: "Venkat",
    place: "MADURAI",
    companyName: "VIMAL MEDICAL AGENCIES",
  },
  {
    contact: "9790120697",
    name: "Venkat",
    place: "MADURAI",
    companyName: "VISHNU PHARMA",
  },
  {
    contact: "9486571648",
    name: "Venkat",
    place: "MADURAI",
    companyName: "VIZAG PHARMA",
  },
  {
    contact: "9842042724",
    name: "Venkat",
    place: "MANAPARAI",
    companyName: "AMBAL AGENCIES",
  },
  {
    contact: "9976609521",
    name: "Venkat",
    place: "MANAPARAI",
    companyName: "GAYATHRI MEDICAL",
  },
  {
    contact: "9965135910",
    name: "Venkat",
    place: "MANAPARAI",
    companyName: "KAVIPUZHAL MEDICALS",
  },
  {
    contact: "9942905271",
    name: "Venkat",
    place: "MANAPARAI",
    companyName: "RAMU ENTERPRISES",
  },
  {
    contact: "8667712938",
    name: "Venkat",
    place: "MANAPARAI",
    companyName: "SHRE SARAVANA MEDICAL AGENCY",
  },
  {
    contact: "7904774433",
    name: "Venkat",
    place: "MANAPARAI",
    companyName: "SRI ANNAPOORANI AGENCY",
  },
  {
    contact: "9443873639",
    name: "Venkat",
    place: "MANAPARAI",
    companyName: "SRI BAALAJI MEDICAL AGENCIES",
  },
  {
    contact: "9524973034",
    name: "Venkat",
    place: "MANAPPARAI",
    companyName: "SRI AMBAL AGENCIES",
  },
  {
    contact: "9962099504",
    name: "Vijaykumar",
    place: "MAYILADUTHURAI",
    companyName: "EMARKEY",
  },
  {
    contact: "7904024852",
    name: "Vijaykumar",
    place: "MEENSURUTI",
    companyName: "UDAYAM PHARMA",
  },
  {
    contact: "9842784028",
    name: "undefined",
    place: "MITTAHALLI ",
    companyName: "VENUS MEDICAL AGENCY",
  },
  {
    contact: "9443332170",
    name: "Venkat",
    place: "NAGERCOIL",
    companyName: "BROTHERS PHARMA",
  },
  {
    contact: "9443264307",
    name: "Venkat",
    place: "NAGERCOIL",
    companyName: "KRISHAL DRUGS & SURGICALS",
  },
  {
    contact: "8903534898",
    name: "Venkat",
    place: "NAGERCOIL",
    companyName: "LEEBANON PHARMA",
  },
  {
    contact: "9345569921",
    name: "Abdullah",
    place: "NAMAKKAL",
    companyName: "ARUL JOTHI AHENCIES",
  },
  {
    contact: "9443963438",
    name: "Abdullah",
    place: "NAMAKKAL",
    companyName: "BALAJI PHARMA SURGICAL",
  },
  {
    contact: "9952802557",
    name: "Abdullah",
    place: "NAMAKKAL",
    companyName: "GREEN PHARMA",
  },
  {
    contact: "9994949614",
    name: "Abdullah",
    place: "NAMAKKAL",
    companyName: "INDIAN PHARMA DISTRIBUTORS",
  },
  {
    contact: "9994151876",
    name: "Abdullah",
    place: "NAMAKKAL",
    companyName: "KAYATHRI PHARMA",
  },
  {
    contact: "9150492949",
    name: "Abdullah",
    place: "NAMAKKAL",
    companyName: "SHREE VARAM AGENCIES",
  },
  {
    contact: "9345655585",
    name: "Abdullah",
    place: "NAMAKKAL",
    companyName: "SHRI BALAGI PHARMA",
  },
  {
    contact: "9787776670",
    name: "Abdullah",
    place: "NAMAKKAL",
    companyName: "SOUTH INDIA PHARAMACEUTICALS-",
  },
  {
    contact: "9344454603",
    name: "Abdullah",
    place: "NAMAKKAL",
    companyName: "SRI AMMAN TRADERS",
  },
  {
    contact: "9344454602",
    name: "Abdullah",
    place: "NAMAKKAL",
    companyName: "SRI AMMAN TRADERS",
  },
  {
    contact: "9994910555",
    name: "Abdullah",
    place: "NAMAKKAL",
    companyName: "SRI VINAYAKA PHARMA",
  },
  {
    contact: "7010611147",
    name: "Vijaykumar",
    place: "NEYVELI",
    companyName: "M R PHARMA AND SURGICAL",
  },
  {
    contact: "9443048988",
    name: "undefined",
    place: "OOTACAMUND",
    companyName: "OOTY DRUG STORES & PHARMACY",
  },
  {
    contact: "9865002108",
    name: "Abdullah",
    place: "PALLADAM",
    companyName: "PALLADAM PHARMA",
  },
  {
    contact: "9842255261",
    name: "Abdullah",
    place: "PALLADAM",
    companyName: "SUBBU AGENCIES",
  },
  {
    contact: "9367430404",
    name: "Vijaykumar",
    place: "PANRUTI",
    companyName: "SAIKRUPA PHARMACEUTICALS",
  },
  {
    contact: "9865464612",
    name: "Venkat",
    place: "PARAMAKUDI",
    companyName: "SAKTHY SURGICAL",
  },
  {
    contact: "7871188977",
    name: "Venkat",
    place: "PARAMAKUDI",
    companyName: "SRI SIVASAKTHI PHARMA",
  },
  {
    contact: "9443129870",
    name: "Venkat",
    place: "PARAMAKUDI",
    companyName: "TIRUPATHY PHRMA",
  },
  {
    contact: "9943572769",
    name: "Venkat",
    place: "PARAMAKUDI",
    companyName: "VIBJAR PHARMA",
  },
  {
    contact: "9443882236",
    name: "Vijaykumar",
    place: "PENNADAM",
    companyName: "SKD PHARMA",
  },
  {
    contact: "9994443888",
    name: "undefined",
    place: "PERAMBALUR",
    companyName: "DEVA PHARMACEUTICALS",
  },
  {
    contact: "9940869343",
    name: "Abdullah",
    place: "PERAMBULUR",
    companyName: "SM PHARMA",
  },
  {
    contact: "9600348517",
    name: "Abdullah",
    place: "POLLACHI",
    companyName: "DHAVANTHRI PHARMA",
  },
  {
    contact: "9866014329",
    name: "Abdullah",
    place: "POLLACHI",
    companyName: "FRIENDS FARMAA",
  },
  {
    contact: "9585688399",
    name: "Abdullah",
    place: "POLLACHI",
    companyName: "KAVIN PHARMA",
  },
  {
    contact: "7373794548",
    name: "Abdullah",
    place: "POLLACHI",
    companyName: "MUTHU PHARMA& SURGICALS",
  },
  {
    contact: "8667399906",
    name: "Abdullah",
    place: "POLLACHI",
    companyName: "S.S PHARMA",
  },
  {
    contact: "9842223121",
    name: "Abdullah",
    place: "POLLACHI",
    companyName: "VIGNESWAR PHARMACEUTICALS",
  },
  {
    contact: "9790049958",
    name: "Vijaykumar",
    place: "PONDICHERRY",
    companyName: "ARC PHARMA",
  },
  {
    contact: "9894399545",
    name: "Vijaykumar",
    place: "PONDICHERRY",
    companyName: "MADHAN SURGICALS",
  },
  {
    contact: "9894178958",
    name: "Vijaykumar",
    place: "PONDICHERRY",
    companyName: "OM SAKTHI AGENCIES",
  },
  {
    contact: "7358806969",
    name: "Vijaykumar",
    place: "PONDICHERRY",
    companyName: "S.S PHARMA",
  },
  {
    contact: "9443872724",
    name: "Vijaykumar",
    place: "PONDICHERRY",
    companyName: "SAKTHI PHARMA",
  },
  {
    contact: "9787066244",
    name: "Vijaykumar",
    place: "PONDICHERRY",
    companyName: "SELVAM PHARMA",
  },
  {
    contact: "9566643678",
    name: "Vijaykumar",
    place: "PONDICHERRY",
    companyName: "SRI AMBAL MEDICAL",
  },
  {
    contact: "9842304776",
    name: "Vijaykumar",
    place: "PONDICHERRY",
    companyName: "SURGICAL POINT",
  },
  {
    contact: "9443480440",
    name: "Vijaykumar",
    place: "PONDICHERRY",
    companyName: "UNION PHARMA",
  },
  {
    contact: "9443287636",
    name: "Vijaykumar",
    place: "PONDICHERRY",
    companyName: "UNITED PHARMA",
  },
  {
    contact: "8489925883",
    name: "Vijaykumar",
    place: "PONDICHERRY",
    companyName: "VAISANVI SURGICALS",
  },
  {
    contact: "9790049958",
    name: "Vijaykumar",
    place: "PUDUCHERRY",
    companyName: "A.R.C.PHARMA",
  },
  {
    contact: "9790580826",
    name: "Vijaykumar",
    place: "PUDUCHERRY",
    companyName: "DINESH AGENCY",
  },
  {
    contact: "9790580826",
    name: "Vijaykumar",
    place: "PUDUCHERRY",
    companyName: "DINESH AGENCY",
  },
  {
    contact: "9442359128",
    name: "Vijaykumar",
    place: "PUDUCHERRY",
    companyName: "SARASWATHI SURGICALS",
  },
  {
    contact: "9345523631",
    name: "Vijaykumar",
    place: "PUDUCHERRY",
    companyName: "SRI AMBALPHARMA",
  },
  {
    contact: "9894022628",
    name: "Vijaykumar",
    place: "PUDUCHERRY",
    companyName: "VAISHNAVI SURGICALS",
  },
  {
    contact: "8489920481",
    name: "Venkat",
    place: "PUDUKKOTTAI",
    companyName: "SIVA PHARMA",
  },
  {
    contact: "7705806880",
    name: "Venkat",
    place: "PUDUKKOTTAI",
    companyName: "SREE SAI PHARMA",
  },
  {
    contact: "9941235123",
    name: "Venkat",
    place: "PUDUKKOTTAI",
    companyName: "VENMAYIL MEDICAL AGENCIES",
  },
  {
    contact: "9842422532",
    name: "Venkat",
    place: "PUDUKKOTTAI",
    companyName: "VENUS CORPORATION",
  },
  {
    contact: "9003741176",
    name: "Venkat",
    place: "PUDUKKOTTAI",
    companyName: "VIJAY MEDICAL AGENCY",
  },
  {
    contact: "9843753619",
    name: "Venkat",
    place: "PUDUKKOTTAI",
    companyName: "VIVEKA PHARMA",
  },
  {
    contact: "8526857880",
    name: "Venkat",
    place: "PUDUKOTTAI",
    companyName: "AJS PHARMA",
  },
  {
    contact: "7339614254",
    name: "Venkat",
    place: "PUDUKOTTAI",
    companyName: "KUMAR AGENCY",
  },
  {
    contact: "9487666426",
    name: "Venkat",
    place: "PUDUKOTTAI",
    companyName: "MLM ENTERPRISES",
  },
  {
    contact: "9952648562",
    name: "Venkat",
    place: "RAJAPALAYAM",
    companyName: "ANDAL MEDICAL AGENCY",
  },
  {
    contact: "9150742702",
    name: "Venkat",
    place: "RAJAPALAYAM",
    companyName: "INDIAN PHARMA",
  },
  {
    contact: "9150742702",
    name: "Venkat",
    place: "RAJAPALAYAM",
    companyName: "INDIAN PHARMA DISTRIBUTOR",
  },
  {
    contact: "9443396554",
    name: "Venkat",
    place: "RAJAPALAYAM",
    companyName: "RAJAPALAYAM PHARMA",
  },
  {
    contact: "9865993467",
    name: "Venkat",
    place: "RAJAPALAYAM",
    companyName: "SRI BOOPATHI PHARMA",
  },
  {
    contact: "9443126184",
    name: "Venkat",
    place: "RAMANATHAPURAM",
    companyName: "ILANGO MEDICAL",
  },
  {
    contact: "9500702368",
    name: "Venkat",
    place: "RAMANATHAPURAM",
    companyName: "SRI RAM CORPORATION",
  },
  {
    contact: "9443322479",
    name: "Venkat",
    place: "RAMANATHAPURAM",
    companyName: "WAZITH MEDICAL CORPORATION",
  },
  {
    contact: "9994367434",
    name: "Abdullah",
    place: "RASIPURAM",
    companyName: "AANDAVAR AGENCIES",
  },
  {
    contact: "9677729171",
    name: "Abdullah",
    place: "RASIPURAM",
    companyName: "AMMAN PHARMA",
  },
  {
    contact: "9994367434",
    name: "Abdullah",
    place: "RASIPURAM",
    companyName: "ANDAVAR AGENCIES",
  },
  {
    contact: "9842056483",
    name: "Abdullah",
    place: "RASIPURAM",
    companyName: "KARTHI PHARMA",
  },
  {
    contact: "9865221163",
    name: "Abdullah",
    place: "RASIPURAM",
    companyName: "MAHALAKSHMI MEDICAL",
  },
  {
    contact: "9790033783",
    name: "Abdullah",
    place: "RASIPURAM",
    companyName: "S S PHARMA",
  },
  {
    contact: "9790033783",
    name: "Abdullah",
    place: "RASIPURAM",
    companyName: "S S PHARMA SURGICAL",
  },
  {
    contact: "9790033783",
    name: "Abdullah",
    place: "RASIPURAM",
    companyName: "S.S MEDICAL AGENCY",
  },
  {
    contact: "9442643119",
    name: "Abdullah",
    place: "RASIPURAM",
    companyName: "SRI DHANALAKSHMI AGENCIES",
  },
  {
    contact: "9655665779",
    name: "Abdullah",
    place: "SALEM",
    companyName: "ANNAMALAI AGENCIES",
  },
  {
    contact: "8508007872",
    name: "Abdullah",
    place: "SALEM",
    companyName: "ARUNA PHARMA &SURGICALS",
  },
  {
    contact: "9443363717",
    name: "Abdullah",
    place: "SALEM",
    companyName: "CAUERY PHARMA",
  },
  {
    contact: "8248422547",
    name: "Abdullah",
    place: "SALEM",
    companyName: "CAUERY PHARMA",
  },
  {
    contact: "9092340490",
    name: "Abdullah",
    place: "SALEM",
    companyName: "GOLD ROSE PHARMA",
  },
  {
    contact: "9629093150",
    name: "Abdullah",
    place: "SALEM",
    companyName: "HINDUSTAN TRADING CORPORATION",
  },
  {
    contact: "9443251100",
    name: "Abdullah",
    place: "SALEM",
    companyName: "JEYASAKTHI AGENCIES",
  },
  {
    contact: "9952793092",
    name: "Abdullah",
    place: "SALEM",
    companyName: "JOEL PHARMA",
  },
  {
    contact: "9842046635",
    name: "Abdullah",
    place: "SALEM",
    companyName: "JS PHARMA",
  },
  {
    contact: "9159090222",
    name: "Abdullah",
    place: "SALEM",
    companyName: "LIFE CARE PHARMACETICALS",
  },
  {
    contact: "7540015555",
    name: "Abdullah",
    place: "SALEM",
    companyName: "MAHALAKSHMI PHARMA",
  },
  {
    contact: "7010128767",
    name: "Abdullah",
    place: "SALEM",
    companyName: "MCR MEDICAL DISTRIBUTORS",
  },
  {
    contact: "9842053505",
    name: "Abdullah",
    place: "SALEM",
    companyName: "MM DRUGS AND SURGICALS",
  },
  {
    contact: "9944574100",
    name: "Abdullah",
    place: "SALEM",
    companyName: "MURUGAN PHARMA",
  },
  {
    contact: "9944614100",
    name: "Abdullah",
    place: "SALEM",
    companyName: "NALAN PHARMA",
  },
  {
    contact: "9944614100",
    name: "Abdullah",
    place: "SALEM",
    companyName: "NANTHINI PHARMA",
  },
  {
    contact: "9842576818",
    name: "Abdullah",
    place: "SALEM",
    companyName: "PHARMA CARE ",
  },
  {
    contact: "9443194070",
    name: "Abdullah",
    place: "SALEM",
    companyName: "PHARMA GALAXY",
  },
  {
    contact: "9677921481",
    name: "Abdullah",
    place: "SALEM",
    companyName: "PKS PHARAMA",
  },
  {
    contact: "99943 81700",
    name: "Abdullah",
    place: "SALEM",
    companyName: "PRIME PHARMA SURGICALS",
  },
  {
    contact: "9842783010",
    name: "Abdullah",
    place: "SALEM",
    companyName: "RAMANY PHARMA",
  },
  {
    contact: "9994950994",
    name: "Abdullah",
    place: "SALEM",
    companyName: "SAKTHI PHARMACEUTICALS",
  },
  {
    contact: "6383732065",
    name: "Abdullah",
    place: "SALEM",
    companyName: "SALEM PHARMA",
  },
  {
    contact: "9677921481",
    name: "Abdullah",
    place: "SALEM",
    companyName: "SHREE PSK PHARMA",
  },
  {
    contact: "9442864887",
    name: "Abdullah",
    place: "SALEM",
    companyName: "SHRI KURINJI PHARMA",
  },
  {
    contact: "7502836330",
    name: "Abdullah",
    place: "SALEM",
    companyName: "SIVASAKTHI AGENCY",
  },
  {
    contact: "9952478971",
    name: "Abdullah",
    place: "SALEM",
    companyName: "SOWMIYA PHARMA SURGICALS",
  },
  {
    contact: "9790373926",
    name: "Abdullah",
    place: "SALEM",
    companyName: "SRI DHAKSHAN PHARMA",
  },
  {
    contact: "9944574100",
    name: "Abdullah",
    place: "SALEM",
    companyName: "SRI MURGAN PHARMACEUTICALS",
  },
  {
    contact: "6383732065",
    name: "Abdullah",
    place: "SALEM",
    companyName: "SRI SALEM PHARMA DISTRIBUTORS",
  },
  {
    contact: "9944622029",
    name: "Abdullah",
    place: "SALEM",
    companyName: "SRI SATHGURU PHARMA",
  },
  {
    contact: "9865412982",
    name: "Abdullah",
    place: "SALEM",
    companyName: "SRM PHARMA",
  },
  {
    contact: "9655191777",
    name: "Abdullah",
    place: "SALEM",
    companyName: "SUNDARAM AGENCIES",
  },
  {
    contact: "9865412982",
    name: "Abdullah",
    place: "SALEM",
    companyName: "THE S.R.M PHARMA SURGICAL",
  },
  {
    contact: "9344429039",
    name: "Abdullah",
    place: "SALEM",
    companyName: "VENKATAVINAYAGA DISTRIBUTORS",
  },
  {
    contact: "9788024175",
    name: "Abdullah",
    place: "SALEM",
    companyName: "WINTECH PHARMA",
  },
  {
    contact: "9865255451",
    name: "Abdullah",
    place: "SALEM ",
    companyName: "FRIENDS PHARMAA",
  },
  {
    contact: "9994941334",
    name: "Abdullah",
    place: "SALEM ",
    companyName: "NANDHINI PHARMACEUTICALS",
  },
  {
    contact: "9578547896",
    name: "Abdullah",
    place: "SALEM ",
    companyName: "SRI MURUGAN PHARMACEUTICALS",
  },
  {
    contact: "9500980556",
    name: "Abdullah",
    place: "SALEM ",
    companyName: "SRI VALLI PHARMA SURGICALS",
  },
  {
    contact: "9092709799",
    name: "Venkat",
    place: "SANKARANKOVIL",
    companyName: "ANNAMALI SURGICAL",
  },
  {
    contact: "9965567353",
    name: "Venkat",
    place: "SANKARANKOVIL",
    companyName: "KRISHNA SURGICAL AND PHARMA",
  },
  {
    contact: "9976847300",
    name: "Venkat",
    place: "SANKARANKOVIL",
    companyName: "SREE ARUNACHALA MEDICAL AGENCI",
  },
  {
    contact: "9887607564",
    name: "Venkat",
    place: "SANKARANKOVIL",
    companyName: "SRI ANNAMALAI SURGICAL&PHARMA",
  },
  {
    contact: "9976847300",
    name: "Venkat",
    place: "SANKARANKOVIL",
    companyName: "SRI ARUNACHALAM PHARMA",
  },
  {
    contact: "9472167351",
    name: "Venkat",
    place: "SANKARANKOVIL",
    companyName: "SRI KRISHA SURGICAL & PHARMA",
  },
  {
    contact: "9659733741",
    name: "Venkat",
    place: "SANKARANKOVIL",
    companyName: "SRI MAHALAKSHMI PHARMA",
  },
  {
    contact: "9994755596",
    name: "Abdullah",
    place: "SATHYAMANGALAM",
    companyName: "SUN MEDICAL AGENCIES",
  },
  {
    contact: "9489846446",
    name: "Venkat",
    place: "SATTUR",
    companyName: "M.M.S MEDICAL STORE",
  },
  {
    contact: "9840348027",
    name: "Venkat",
    place: "SATTUR",
    companyName: "MAHESH MEDICAL AGENCIES",
  },
  {
    contact: "9443569162",
    name: "Venkat",
    place: "SIVAGANGA",
    companyName: "MEENAKSHI AGENCIES",
  },
  {
    contact: "9789620286",
    name: "Venkat",
    place: "SIVAGANGAI",
    companyName: "MALLIKA AGENCIES",
  },
  {
    contact: "9943148706",
    name: "Venkat",
    place: "SIVAKASI",
    companyName: "DHANALAKSHMI MEDICAL AGENCIES",
  },
  {
    contact: "9150342280",
    name: "Venkat",
    place: "SIVAKASI",
    companyName: "FRIENDS PHARMA",
  },
  {
    contact: "9943364522",
    name: "Venkat",
    place: "SIVAKASI",
    companyName: "MALAIAMMAN MEDICAL AGENCIES",
  },
  {
    contact: "9367628899",
    name: "Venkat",
    place: "SIVAKASI",
    companyName: "MEDITEK HEALTHCARE INC",
  },
  {
    contact: "9788856266",
    name: "Venkat",
    place: "SIVAKASI",
    companyName: "SANKAR PHARMA",
  },
  {
    contact: "6382173646",
    name: "Venkat",
    place: "SIVAKASI",
    companyName: "SANKAR PHARMA SURGICALSS",
  },
  {
    contact: "9842990009",
    name: "Venkat",
    place: "SIVAKASI",
    companyName: "SHANKAR PHARMA SURGICALSS",
  },
  {
    contact: "9750630222",
    name: "Venkat",
    place: "SIVAKASI",
    companyName: "TIRUPATHI PHARMA",
  },
  {
    contact: "9488345822",
    name: "Venkat",
    place: "SIVAKASI",
    companyName: "VILVAM PHARMA",
  },
  {
    contact: "9080590259",
    name: "Venkat",
    place: "TENKASI",
    companyName: "LOGANAYAGE DRUGS",
  },
  {
    contact: "9842453700",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "A.V. R. PHARMACEUTICALS",
  },
  {
    contact: "9945533834",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "AADHI AGENCIES",
  },
  {
    contact: "9952788087",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "GANAPATHY DRUG STORE",
  },
  {
    contact: "9443125216",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "J. S. PHARMACEUTICAL DISTRIBUTORS",
  },
  {
    contact: "9786836649",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "NIRMAL PHARMA",
  },
  {
    contact: "7094341069",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "PRATHANA MANTHRI BHARTIYA",
  },
  {
    contact: "9647678084",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "RB PHARMA DISTRIBUTORS",
  },
  {
    contact: "9788117987",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "REXTAN PHARMA",
  },
  {
    contact: "9940893319",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "SARGURU PHARMA",
  },
  {
    contact: "9047546424",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "SATHAA DRUGS",
  },
  {
    contact: "9443112277",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "SHIVALAYA PHARMA",
  },
  {
    contact: "9443407487",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "SIVAM PHARMACEUTICALS",
  },
  {
    contact: "9443872969",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "SRI SAI GANAPATHY PHARMA",
  },
  {
    contact: "7200484894",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "SRI SAI RAM PHARMA",
  },
  {
    contact: "9940998388",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "V V PHARMA",
  },
  {
    contact: "9894868123",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "VASAN MEDICAL AGENCIES",
  },
  {
    contact: "8056440736",
    name: "Vijaykumar",
    place: "THANJAVUR",
    companyName: "VEDHA MEDICARE",
  },
  {
    contact: "9790019491",
    name: "Venkat",
    place: "THENI",
    companyName: "AMRITHA PHARMA DISTRIBUTORS",
  },
  {
    contact: "9751673616",
    name: "Venkat",
    place: "THENI",
    companyName: "KEVIN PHARMA AGENCY",
  },
  {
    contact: "9445226218",
    name: "Abdullah",
    place: "THENI",
    companyName: "LIFE CARE",
  },
  {
    contact: "9965482550",
    name: "Venkat",
    place: "THENI",
    companyName: "S S PHARMA",
  },
  {
    contact: "9952212814",
    name: "Venkat",
    place: "THENI",
    companyName: "SRI SAAI PHARMA",
  },
  {
    contact: "9843324454",
    name: "Venkat",
    place: "THENI",
    companyName: "THENI SURGICALS",
  },
  {
    contact: "8608215572",
    name: "Venkat",
    place: "THENI",
    companyName: "VAISHNAVI PHARMA",
  },
  {
    contact: "8015225512",
    name: "Venkat",
    place: "THENKASI",
    companyName: "SARAVANA PHARMA",
  },
  {
    contact: "6374357716",
    name: "Venkat",
    place: "THIRUNELVELI",
    companyName: "ANBU DRUGS",
  },
  {
    contact: "9994945443",
    name: "Abdullah",
    place: "THIRUPATTUR",
    companyName: "SARAVANA PHARMA",
  },
  {
    contact: "9123526266",
    name: "Abdullah",
    place: "THIRUPATTUR",
    companyName: "SRI BALAJI PHARMA",
  },
  {
    contact: "8667862561",
    name: "Abdullah",
    place: "THIRUPATTUR",
    companyName: "SRI LAKSHMI AGENCIES",
  },
  {
    contact: "9500449588",
    name: "Abdullah",
    place: "THIRUPATTUR",
    companyName: "SRI SHANMUNDI PHARMA",
  },
  {
    contact: "9486843389",
    name: "Abdullah",
    place: "THIRUPATTUR",
    companyName: "SRINIVASA PHARMA",
  },
  {
    contact: "9443201027",
    name: "undefined",
    place: "THIRUTHURAIPOONDI ",
    companyName: "CINNAMMAL DRUG TRADE",
  },
  {
    contact: "9791020678",
    name: "Prem",
    place: "THIRUVALLUR",
    companyName: "SRI VARI MEDICAL PHARMA",
  },
  {
    contact: "9095622232",
    name: "Vijaykumar",
    place: "THIRUVANNAMALAI",
    companyName: "ARUNA AGENCIES",
  },
  {
    contact: "9786717855",
    name: "Vijaykumar",
    place: "THIRUVANNAMALAI",
    companyName: "HARI PHARMA",
  },
  {
    contact: "9551650275",
    name: "Vijaykumar",
    place: "THIRUVANNAMALAI",
    companyName: "KARPAGAM PHARMA",
  },
  {
    contact: "7904692015",
    name: "Vijaykumar",
    place: "THIRUVANNAMALAI",
    companyName: "RAMANA PHARMA",
  },
  {
    contact: "94442492694",
    name: "Vijaykumar",
    place: "THIRUVANNAMALAI",
    companyName: "SRI SIVA PHARMA",
  },
  {
    contact: "9443149681",
    name: "Vijaykumar",
    place: "THIRUVANNAMALAI",
    companyName: "SRI VENKATESWARA AGENCIES",
  },
  {
    contact: "9789210907",
    name: "Vijaykumar",
    place: "THIRUVANNAMALAI",
    companyName: "SVR PHARMA",
  },
  {
    contact: "7904100467",
    name: "Vijaykumar",
    place: "THIRUVANNAMALAI",
    companyName: "SWASTIK AGENCIES",
  },
  {
    contact: "9443243302",
    name: "Vijaykumar",
    place: "THIRUVARUR",
    companyName: "SRI LAKSHMI AGENCIES",
  },
  {
    contact: "9443448708",
    name: "Vijaykumar",
    place: "THIRUVARUR",
    companyName: "STEVE AND MARKS PHARMACEUTICALS",
  },
  {
    contact: "9843090550",
    name: "Vijaykumar",
    place: "THIRUVARUR",
    companyName: "UNICORN PHARMACEUTICAL",
  },
  {
    contact: "9092425041",
    name: "Venkat",
    place: "TIRUCHIRAPPALLI",
    companyName: "ANGU PHARMA",
  },
  {
    contact: "9943619252",
    name: "Vijaykumar",
    place: "TIRUKOVILUR",
    companyName: "G V PHARMA",
  },
  {
    contact: "9159131836",
    name: "Vijaykumar",
    place: "TIRUKOVILUR",
    companyName: "SURESH PHARMA",
  },
  {
    contact: "8940263053",
    name: "Venkat",
    place: "TIRUNELVELI ",
    companyName: "MANI PHARMACEUTICALS",
  },
  {
    contact: "9894720007",
    name: "Venkat",
    place: "TIRUNELVELI ",
    companyName: "NATARAJA ENTERPRISES",
  },
  {
    contact: "9443520004",
    name: "Venkat",
    place: "TIRUNELVELI ",
    companyName: "PHARMA DARSHAN PHARMACEUTICAL DISTRIBUTO",
  },
  {
    contact: "9047056309",
    name: "Venkat",
    place: "TIRUNELVELI ",
    companyName: "VIJAYA ENTERPRISES",
  },
  {
    contact: "7845777565",
    name: "Venkat",
    place: "TIRUNELVELI ",
    companyName: "VIJAYA PHARMACEUTICALS",
  },
  {
    contact: "8668111420",
    name: "Abdullah",
    place: "TIRUPATTUR",
    companyName: "AKS AGENCY",
  },
  {
    contact: "9865253007",
    name: "Abdullah",
    place: "TIRUPATTUR",
    companyName: "SRI MAGALAKSHMI PHARMA",
  },
  {
    contact: "9443810009",
    name: "Abdullah",
    place: "TIRUPATTUR",
    companyName: "SRI RANGA MEDICALS",
  },
  {
    contact: "9443328837",
    name: "Abdullah",
    place: "TIRUPPATTUR",
    companyName: "SREE RASI PHARMA AGENCIES",
  },
  {
    contact: "9095225888",
    name: "Abdullah",
    place: "TIRUPPUR",
    companyName: "SHIFA PHARMA SURGICALS",
  },
  {
    contact: "9865035914",
    name: "Abdullah",
    place: "TIRUPUR",
    companyName: "DIVINE PHARMA",
  },
  {
    contact: "9994833766",
    name: "Abdullah",
    place: "TIRUPUR",
    companyName: "JEEVIKA PHARMA",
  },
  {
    contact: "9677776600",
    name: "Abdullah",
    place: "TIRUPUR",
    companyName: "KOTHAI PHARMA",
  },
  {
    contact: "9789733440",
    name: "Abdullah",
    place: "TIRUPUR",
    companyName: "M M PHAMRA",
  },
  {
    contact: "9788952541",
    name: "Abdullah",
    place: "TIRUPUR",
    companyName: "NEW SAKTHI MEDICAL",
  },
  {
    contact: "9865076751",
    name: "Abdullah",
    place: "TIRUPUR",
    companyName: "RECEIPE PHARMA",
  },
  {
    contact: "9944301222",
    name: "Abdullah",
    place: "TIRUPUR",
    companyName: "SRI AMMAN PHARMA",
  },
  {
    contact: "9894322766",
    name: "Abdullah",
    place: "TIRUPUR",
    companyName: "SUN SUN DRUG",
  },
  {
    contact: "9994404045",
    name: "Abdullah",
    place: "TIRUPUR",
    companyName: "TIRUPATHY PHARMA",
  },
  {
    contact: "9047457278",
    name: "Abdullah",
    place: "TIRUPUR",
    companyName: "VIRUTCHA AGENCIES",
  },
  {
    contact: "9597447727",
    name: "Vijaykumar",
    place: "TIRUVANNAMALAI ",
    companyName: "BISMI AGENCIES",
  },
  {
    contact: "9443149681",
    name: "Vijaykumar",
    place: "TIRUVANNAMALAI ",
    companyName: "SRI VENKATESHWARA AGENCIES",
  },
  {
    contact: "9655535111",
    name: "Vijaykumar",
    place: "TIRUVANNAMALI",
    companyName: "ANDAL MEDICAL AGENCY",
  },
  {
    contact: "9442058953",
    name: "Vijaykumar",
    place: "TITTAGUDI",
    companyName: "MEENAKSHI AGENCIES",
  },
  {
    contact: "9443145000",
    name: "Venkat",
    place: "TRICHY",
    companyName: "A.K.S AGENCIES",
  },
  {
    contact: "9443189929",
    name: "Venkat",
    place: "TRICHY",
    companyName: "KASIRAJ AGENCIES",
  },
  {
    contact: "9943203166",
    name: "Venkat",
    place: "TRICHY",
    companyName: "MUTHU MEENA MEDICALS",
  },
  {
    contact: "7094446135",
    name: "Venkat",
    place: "TRICHY",
    companyName: "VenkatESHWARA PHARMACEUTICALS",
  },
  {
    contact: "9842372666",
    name: "Venkat",
    place: "TRICHY",
    companyName: "YASHNA PHARMA",
  },
  {
    contact: "9843855088",
    name: "Venkat",
    place: "TRICHY",
    companyName: "YUVANAA ENTERPRISES",
  },
  {
    contact: "9894430667",
    name: "Abdullah",
    place: "UDUMALPET",
    companyName: "AADHITHYA PHARMA",
  },
  {
    contact: "8124108384",
    name: "Abdullah",
    place: "UDUMALPET",
    companyName: "ADITYA PHARMA",
  },
  {
    contact: "9894295126",
    name: "Abdullah",
    place: "UDUMALPET",
    companyName: "DELUXE MEDICAL",
  },
  {
    contact: "9791975366",
    name: "Abdullah",
    place: "UDUMALPET",
    companyName: "HIMALAYA PHARMA",
  },
  {
    contact: "9865028111",
    name: "Abdullah",
    place: "UDUMALPET",
    companyName: "SENTHIL PHARMA ",
  },
  {
    contact: "9486371868",
    name: "Abdullah",
    place: "UTHANGARAI",
    companyName: "SREE MARUTHI PHARMA AGENCIES",
  },
  {
    contact: "9443487174",
    name: "Venkat",
    place: "Vallioor",
    companyName: "RAGU SURGICALS",
  },
  {
    contact: "9361046060",
    name: "Abdullah",
    place: "VANIYAMBADI",
    companyName: "GOLDEN PHARMA",
  },
  {
    contact: "9994414794",
    name: "Prem",
    place: "VELLORE",
    companyName: "ARUN PHARMA AGENCIES",
  },
  {
    contact: "9363237760",
    name: "Prem",
    place: "VELLORE",
    companyName: "EUREKHA PHARMA",
  },
  {
    contact: "8870772499",
    name: "Prem",
    place: "VELLORE",
    companyName: "SHREE GAJALAKSHMI  PHARMACEUTICALS",
  },
  {
    contact: "9944033308",
    name: "Prem",
    place: "VELLORE",
    companyName: "SRI SARAVANA PHARMA",
  },
  {
    contact: "9944353237",
    name: "Prem",
    place: "VELLORE",
    companyName: "SRI VENKESWARA DRUG HOUSE",
  },
  {
    contact: "9344548797",
    name: "Prem",
    place: "VELLORE",
    companyName: "SRI VIGNESH DRUG HOUSE",
  },
  {
    contact: "9944331735",
    name: "Prem",
    place: "VELLORE",
    companyName: "TAAG PHARMACEUTICALS",
  },
  {
    contact: "9843643765",
    name: "Prem",
    place: "VELLORE",
    companyName: "VIJAYABHARATHI PHARMA",
  },
  {
    contact: "9698137701",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "ANNAI PHARMA",
  },
  {
    contact: "8015874522",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "ANNAMALAIYAR AGENCIES",
  },
  {
    contact: "9488645159",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "ARUNAI AGENCIES",
  },
  {
    contact: "9443292300",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "BHARANI AGENCY",
  },
  {
    contact: "9962099304",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "MASHA PHARMA",
  },
  {
    contact: "9566884086",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "ORANGE PHARMA & SURGICAL",
  },
  {
    contact: "9444224433",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "PALANIYAPPA PHARMACEUTICALS",
  },
  {
    contact: "9787170638",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "PERICURE PHARMA",
  },
  {
    contact: "9865438251",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "RAJINI PHARMA",
  },
  {
    contact: "9894287516",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "RAMACHANDRA PHARMA",
  },
  {
    contact: "9994939888",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "RAMLAKSHMAN AGENCIES",
  },
  {
    contact: "9443227178",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "SAI RAM PHARMA",
  },
  {
    contact: "8489928475",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "SARASWATHI PHARMA AGENCIES",
  },
  {
    contact: "9944779635",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "SRI DHARANI AGENCY",
  },
  {
    contact: "9443737839",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "SRI JAIGANESH AGENCIES",
  },
  {
    contact: "9976974024",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "THIRUPATHI AGENCIES",
  },
  {
    contact: "9944354632",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "UMAIYAL AGENCIES",
  },
  {
    contact: "9865197467",
    name: "Vijaykumar",
    place: "VILLUPURAM",
    companyName: "VAIRAM PHARMA",
  },
  {
    contact: "9585701425",
    name: "Vijaykumar",
    place: "VILUPPURAM",
    companyName: "SANA MEDICAL DISTRIBUTOR",
  },
  {
    contact: "9944289316",
    name: "Vijaykumar",
    place: "VIRUDHACHALAM",
    companyName: "DEVADHA PHARMA",
  },
  {
    contact: "9443080028",
    name: "Vijaykumar",
    place: "VIRUDHACHALAM",
    companyName: "JAYA PHARMA AGENCY",
  },
  {
    contact: "9865432443",
    name: "Vijaykumar",
    place: "VIRUDHACHALAM",
    companyName: "KARPAGA VINAYAGA AGENCIES",
  },
  {
    contact: "9551650271",
    name: "Vijaykumar",
    place: "VIRUDHACHALAM",
    companyName: "SRI KARPAGA VINAYAGA AGENCY",
  },
  {
    contact: "9659383940",
    name: "Vijaykumar",
    place: "VIRUDHACHALAM",
    companyName: "VASANTHA PHARMA AGENCIES",
  },
  {
    contact: "7373755805",
    name: "Venkat",
    place: "VIRUDHUNAGAR",
    companyName: "GURULAKSHMI MEDICAL AGENCIES",
  },
  {
    contact: "9842149553",
    name: "Venkat",
    place: "VIRUDHUNAGAR",
    companyName: "MOHAN MEDICAL AGENCIES",
  },
  {
    contact: "9952806492",
    name: "Venkat",
    place: "VIRUDHUNAGAR",
    companyName: "SENTHILNATHAN PHARMA",
  },
  {
    contact: "8072652013",
    name: "Venkat",
    place: "VIRUDHUNAGAR",
    companyName: "SHANMUGA MEDICAL HALL ",
  },
  {
    contact: "9715857382",
    name: "Venkat",
    place: "VIRUDHUNAGAR",
    companyName: "SPK PHARMA",
  },
  {
    contact: "9965560087",
    name: "Venkat",
    place: "VIRUDHUNAGAR",
    companyName: "SWATHI ENTERPRISES",
  },
  {
    contact: "9750630222",
    name: "Venkat",
    place: "VIRUDHUNAGAR",
    companyName: "THIRUPATHI PHARMA",
  },
  {
    contact: "8012510099",
    name: "Venkat",
    place: "VIRUTHUNAGAR",
    companyName: "SOURNA LAKSHMI MEDICAL AGENCY",
  },
];

