export const contacts = [
  {
    contact: "8056063139",
    name: "Vishal",
    companyName: "Sociallink",
  },
  {
    contact: "8489767296",
    name: "Winfred",
    companyName: "NexGen Labs",
  },

  {
    contact: "8089678967",
    name: "Prabhu",
    companyName: "NexGen Labs",
  },
  {
    contact: "8249554989",
    name: "Kushal",
    companyName: "NexGen Labs",
  },
  {
    contact: "7904172010",
    name: "Nexgen meds",
    companyName: "NexGen Labs",
  },
  {
    contact: "9962581190",
    name: "Karthik",
    companyName: "NexGen Labs",
  },
  {
    contact: "9790895396",
    name: "Surya",
    companyName: "NexGen Labs",
  },
  {
    contact: "9790953563",
    name: "Subramani",
    companyName: "NexGen Labs",
  },
  { contact: "9150351693", companyName: "A R P PHARMA", name: "A R P PHARMA" },
  {
    contact: "9442627876",
    companyName: "A. R. C. AGENCIES - DINDIGUL",
    name: "A. R. C. AGENCIES - DINDIGUL",
  },
  { contact: "9944778123", companyName: "A.V. PHARMA", name: "A.V. PHARMA" },
  {
    contact: "9842453700",
    companyName: "A.V. R. PHARMACEUTICALS- THANJAVUR",
    name: "A.V. R. PHARMACEUTICALS- THANJAVUR",
  },
  {
    contact: "9945533834",
    companyName: "AADHI AGENCIES",
    name: "AADHI AGENCIES",
  },
  {
    contact: "9894430667",
    companyName: "AADHITHYA PHARMA",
    name: "AADHITHYA PHARMA",
  },
  {
    contact: "9994367434",
    companyName: "AANDAVAR AGENCIES",
    name: "AANDAVAR AGENCIES",
  },
  {
    contact: "9842722812",
    companyName: "ABIRAMI MEDICAL AGENCIES",
    name: "ABIRAMI MEDICAL AGENCIES",
  },
  {
    contact: "9841457207",
    companyName: "ABIRAMI MEDICAL AGENCIES",
    name: "ABIRAMI MEDICAL AGENCIES",
  },
  {
    contact: "8122335588",
    companyName: "ABIRAMI PHARMA CENTRE - MADURAI",
    name: "ABIRAMI PHARMA CENTRE - MADURAI",
  },
  { contact: "7598361229", companyName: "ABS FIRM", name: "ABS FIRM" },
  { contact: "9345301954", companyName: "AGS PHARMA", name: "AGS PHARMA" },
  {
    contact: "8098467387",
    companyName: "AISHWARIYA PHARMA",
    name: "AISHWARIYA PHARMA",
  },
  {
    contact: "9344720864",
    companyName: "AISHWARYA PHARMA",
    name: "AISHWARYA PHARMA",
  },
  { contact: "8526857880", companyName: "AJS PHARMA", name: "AJS PHARMA" },
  { contact: "9842220985", companyName: "AKASH PHARMA", name: "AKASH PHARMA" },
  { contact: "8668111420", companyName: "AKS AGENCY", name: "AKS AGENCY" },
  { contact: "9500827485", companyName: "ALAMU PHARMA", name: "ALAMU PHARMA" },
  {
    contact: "9282174222",
    companyName: "ALL POWER SYSTEM",
    name: "ALL POWER SYSTEM",
  },
  {
    contact: "9344520001",
    companyName: "ALLAINCE LIFE SCIENCE",
    name: "ALLAINCE LIFE SCIENCE",
  },
  { contact: "8825818180", companyName: "ALPHA PHARMA", name: "ALPHA PHARMA" },
  {
    contact: "9842042724",
    companyName: "AMBAL AGENCIES",
    name: "AMBAL AGENCIES",
  },
  { contact: "7418383210", companyName: "AMITY PHARMA", name: "AMITY PHARMA" },
  { contact: "6381835903", companyName: "AMITY PHARMA", name: "AMITY PHARMA" },
  {
    contact: "9962285399",
    companyName: "AMMAN AGENCIES",
    name: "AMMAN AGENCIES",
  },
  { contact: "9176763789", companyName: "AMMAN DRUGS", name: "AMMAN DRUGS" },
  {
    contact: "8862236064",
    companyName: "AMMAN HEALTH CARE",
    name: "AMMAN HEALTH CARE",
  },
  {
    contact: "9443722353",
    companyName: "AMMAN MEDICAL AGENCIES",
    name: "AMMAN MEDICAL AGENCIES",
  },
  { contact: "9677729171", companyName: "AMMAN PHARMA", name: "AMMAN PHARMA" },
  { contact: "9842307595", companyName: "AMMAN PHARMA", name: "AMMAN PHARMA" },
  {
    contact: "9626334340",
    companyName: "AMMAN PHARMA DISTRIBUTORS",
    name: "AMMAN PHARMA DISTRIBUTORS",
  },
  {
    contact: "9443471063",
    companyName: "AMPA SHRI PHARMA",
    name: "AMPA SHRI PHARMA",
  },
  {
    contact: "9790019491",
    companyName: "AMRITHA PHARMA DISTRIBUTORS",
    name: "AMRITHA PHARMA DISTRIBUTORS",
  },
  {
    contact: "9942448743",
    companyName: "ANAND MEDICAL AGENCY",
    name: "ANAND MEDICAL AGENCY",
  },
  {
    contact: "9842374242",
    companyName: "ANAND PHARMA AGENCY - THENI",
    name: "ANAND PHARMA AGENCY - THENI",
  },
  { contact: "6374357716", companyName: "ANBU DRUGS", name: "ANBU DRUGS" },
  {
    contact: "9655535111",
    companyName: "ANDAL MEDICAL AGENCY",
    name: "ANDAL MEDICAL AGENCY",
  },
  {
    contact: "9952648562",
    companyName: "ANDAL MEDICAL AGENCY",
    name: "ANDAL MEDICAL AGENCY",
  },
  { contact: "9092425041", companyName: "ANGU PHARMA", name: "ANGU PHARMA" },
  { contact: "9098425047", companyName: "ANGU PHARMA", name: "ANGU PHARMA" },
  {
    contact: "9750254757",
    companyName: "ANITHA  MEDICAL AGENCIES",
    name: "ANITHA  MEDICAL AGENCIES",
  },
  { contact: "9698137701", companyName: "ANNAI PHARMA", name: "ANNAI PHARMA" },
  {
    contact: "9865999956",
    companyName: "ANNAMALAI AGENCIES",
    name: "ANNAMALAI AGENCIES",
  },
  {
    contact: "8015874522",
    companyName: "ANNAMALAIYAR AGENCIES-VILLUPURAM",
    name: "ANNAMALAIYAR AGENCIES-VILLUPURAM",
  },
  {
    contact: "9092709799",
    companyName: "ANNAMALI SURGICAL",
    name: "ANNAMALI SURGICAL",
  },
  {
    contact: "9994819766",
    companyName: "APM MEDICAL AGENCIES",
    name: "APM MEDICAL AGENCIES",
  },
  {
    contact: "9994977323",
    companyName: "APOLLO PHARMA",
    name: "APOLLO PHARMA",
  },
  { contact: "9043112251", companyName: "AR PHARMA", name: "AR PHARMA" },
  {
    contact: "9894206699",
    companyName: "ARHAM HEALTH CARE ",
    name: "ARHAM HEALTH CARE ",
  },
  { contact: "9840322379", companyName: "ARJUN PHARMA", name: "ARJUN PHARMA" },
  { contact: "9750351725", companyName: "ARP PHARMA", name: "ARP PHARMA" },
  {
    contact: "9434282311",
    companyName: "ARSUNA AGENCIES - PORT BLAIR",
    name: "ARSUNA AGENCIES - PORT BLAIR",
  },
  {
    contact: "9688188666",
    companyName: "ARUL ENTERPRISES",
    name: "ARUL ENTERPRISES",
  },
  {
    contact: "9345569921",
    companyName: "ARUL JOTHI AHENCIES",
    name: "ARUL JOTHI AHENCIES",
  },
  {
    contact: "9994414794",
    companyName: "ARUN PHARMA AGENCIES",
    name: "ARUN PHARMA AGENCIES",
  },
  {
    contact: "9095622232",
    companyName: "ARUNA AGENCIES",
    name: "ARUNA AGENCIES",
  },
  {
    contact: "8508007872",
    companyName: "ARUNA PHARMA &SURGICALS",
    name: "ARUNA PHARMA &SURGICALS",
  },
  {
    contact: "9488645159",
    companyName: "ARUNAI AGENCIES",
    name: "ARUNAI AGENCIES",
  },
  {
    contact: "9600075374",
    companyName: "ASVISH PHARMA AGENCIES",
    name: "ASVISH PHARMA AGENCIES",
  },
  { contact: "9597943678", companyName: "AT PHARMA", name: "AT PHARMA" },
  {
    contact: "9345294252",
    companyName: "AZAGAR DISTRIBUTORS",
    name: "AZAGAR DISTRIBUTORS",
  },
  {
    contact: "9442272030",
    companyName: "BAGAVATHI & CO",
    name: "BAGAVATHI & CO",
  },
  {
    contact: "9444497764",
    companyName: "BAIRAVAA AGENCIES",
    name: "BAIRAVAA AGENCIES",
  },
  {
    contact: "9597833798",
    companyName: "BAKIYALAKSHMI AGENCIES",
    name: "BAKIYALAKSHMI AGENCIES",
  },
  {
    contact: "7402623083",
    companyName: "BALA SARASWATHI SURGICALS AND PHARMACEUT",
    name: "BALA SARASWATHI SURGICALS AND PHARMACEUT",
  },
  {
    contact: "9629034433",
    companyName: "BALAJI AGENCIES",
    name: "BALAJI AGENCIES",
  },
  {
    contact: "9443963438",
    companyName: "BALAJI PHARMA SURGICAL",
    name: "BALAJI PHARMA SURGICAL",
  },
  {
    contact: "9976023083",
    companyName: "BALASARASWATHI SURGICAL & PHARMACEUTICAL",
    name: "BALASARASWATHI SURGICAL & PHARMACEUTICAL",
  },
  {
    contact: "8072459830",
    companyName: "BARANI AGENCIES",
    name: "BARANI AGENCIES",
  },
  {
    contact: "9443292300",
    companyName: "BARANI AGENCIES-VILLUPURAM",
    name: "BARANI AGENCIES-VILLUPURAM",
  },
  { contact: "7010414240", companyName: "BELL PHARMA", name: "BELL PHARMA" },
  {
    contact: "9443292300",
    companyName: "BHARANI AGENCY",
    name: "BHARANI AGENCY",
  },
  {
    contact: "7975183471",
    companyName: "BHAVESH DISTRIBUTOR",
    name: "BHAVESH DISTRIBUTOR",
  },
  {
    contact: "9884585898",
    companyName: "BHIKSHU PHARMA DISTRIBUTORS",
    name: "BHIKSHU PHARMA DISTRIBUTORS",
  },
  {
    contact: "9597447727",
    companyName: "BISMI AGENCIES",
    name: "BISMI AGENCIES",
  },
  {
    contact: "9941141600",
    companyName: "BRITISH PHARMA",
    name: "BRITISH PHARMA",
  },
  { contact: "8870663039", companyName: "C J PHARMA", name: "C J PHARMA" },
  {
    contact: "8072725055",
    companyName: "CARE ENTERPRICES",
    name: "CARE ENTERPRICES",
  },
  {
    contact: "9443851606",
    companyName: "CITY DRUDS & SURGICAL",
    name: "CITY DRUDS & SURGICAL",
  },
  {
    contact: "9344017280",
    companyName: "CITY PHARMA - COIMBATORE",
    name: "CITY PHARMA - COIMBATORE",
  },
  {
    contact: "9486844444",
    companyName: "CLOSED VIJAY PHARMA",
    name: "CLOSED VIJAY PHARMA",
  },
  {
    contact: "9444041789",
    companyName: "CRYSTAL HELTH CARE",
    name: "CRYSTAL HELTH CARE",
  },
  { contact: "9361502274", companyName: "CURE PHARMA", name: "CURE PHARMA" },
  {
    contact: "9444063994",
    companyName: "D N KISHORE PHARMA",
    name: "D N KISHORE PHARMA",
  },
  {
    contact: "9840291001",
    companyName: "DADA GANESH PHARMACEUTICALS",
    name: "DADA GANESH PHARMACEUTICALS",
  },
  {
    contact: "9894295126",
    companyName: "DELUXE MEDICAL",
    name: "DELUXE MEDICAL",
  },
  {
    contact: "9944317112",
    companyName: "DEVA MEDICAL AGENCY",
    name: "DEVA MEDICAL AGENCY",
  },
  {
    contact: "9994443888",
    companyName: "DEVA PHARMACEUTICALS",
    name: "DEVA PHARMACEUTICALS",
  },
  {
    contact: "9943148706",
    companyName: "DHANALAKSHMI MEDICAL AGENCIES",
    name: "DHANALAKSHMI MEDICAL AGENCIES",
  },
  {
    contact: "9965619539",
    companyName: "DHANVANTHIRI PHARMACEUTICALS",
    name: "DHANVANTHIRI PHARMACEUTICALS",
  },
  {
    contact: "9840510652",
    companyName: "DHANVANTHRI MEDICAL AGENCIES",
    name: "DHANVANTHRI MEDICAL AGENCIES",
  },
  {
    contact: "9894283250",
    companyName: "DHARANI MEDICAL AGENCIES",
    name: "DHARANI MEDICAL AGENCIES",
  },
  {
    contact: "9600972208",
    companyName: "DHARSHAN PHARMA",
    name: "DHARSHAN PHARMA",
  },
  {
    contact: "9025718068",
    companyName: "DHARSHAN PHARMA",
    name: "DHARSHAN PHARMA",
  },
  {
    contact: "9600348517",
    companyName: "DHAVANTHRI PHARMA",
    name: "DHAVANTHRI PHARMA",
  },
  {
    contact: "9994066377",
    companyName: "DHEERAN PHARMA",
    name: "DHEERAN PHARMA",
  },
  {
    contact: "9941334930",
    companyName: "DHEIVA MEDICAL AGENCY",
    name: "DHEIVA MEDICAL AGENCY",
  },
  {
    contact: "9944298508",
    companyName: "DHIYANA LINGA MEDICAL",
    name: "DHIYANA LINGA MEDICAL",
  },
  {
    contact: "9790580826",
    companyName: "DINESH AGENCY",
    name: "DINESH AGENCY",
  },
  {
    contact: "9865035914",
    companyName: "DIVINE PHARMA",
    name: "DIVINE PHARMA",
  },
  {
    contact: "9442387892",
    companyName: "DOLLAR PHARMACY",
    name: "DOLLAR PHARMACY",
  },
  { contact: "9840585346", companyName: "DR. PHARMA", name: "DR. PHARMA" },
  { contact: "9944777888", companyName: "DR.FAZIL", name: "DR.FAZIL" },
  {
    contact: "9941343888",
    companyName: "DRAVID SURGICALS&PHARMA AGENCIES",
    name: "DRAVID SURGICALS&PHARMA AGENCIES",
  },
  {
    contact: "9489600379",
    companyName: "DRUG AND CARE ONLINE PHARMACY",
    name: "DRUG AND CARE ONLINE PHARMACY",
  },
  {
    contact: "9445097795",
    companyName: "DRUG INSPECTOR",
    name: "DRUG INSPECTOR",
  },
  {
    contact: "9962977380",
    companyName: "DX3 AGENCY DRUG & SUGICALS",
    name: "DX3 AGENCY DRUG & SUGICALS",
  },
  {
    contact: "9443145321",
    companyName: "DYNAMIC MARKETING",
    name: "DYNAMIC MARKETING",
  },
  {
    contact: "9894922811",
    companyName: "EEGAMAI AGENCIES",
    name: "EEGAMAI AGENCIES",
  },
  {
    contact: "9962099504",
    companyName: "EMARKEY PHARMA",
    name: "EMARKEY PHARMA",
  },
  {
    contact: "9940420079",
    companyName: "EMMANUEL PHARMA &SUGICALS",
    name: "EMMANUEL PHARMA &SUGICALS",
  },
  {
    contact: "9884472619",
    companyName: "EMSON PHARMACEUTICALS",
    name: "EMSON PHARMACEUTICALS",
  },
  { contact: "9629093150", companyName: "ERODE PHARMA", name: "ERODE PHARMA" },
  {
    contact: "9566247085",
    companyName: "ESWAR PHARMA AND SURGICALS",
    name: "ESWAR PHARMA AND SURGICALS",
  },
  {
    contact: "7639077314",
    companyName: "EUREKHA PHARMA",
    name: "EUREKHA PHARMA",
  },
  {
    contact: "9840976206",
    companyName: "EVEREST PHARMA DISTRIBUTORS",
    name: "EVEREST PHARMA DISTRIBUTORS",
  },
  {
    contact: "8973773585",
    companyName: "EVEREST PHARMACETICALS",
    name: "EVEREST PHARMACETICALS",
  },
  {
    contact: "9629197934",
    companyName: "EVEREST PHARMACEUTICALS",
    name: "EVEREST PHARMACEUTICALS",
  },
  { contact: "9443855582", companyName: "EXCEL PHARMA", name: "EXCEL PHARMA" },
  {
    contact: "9840798447",
    companyName: "F.SAMPATH PHARMACEUTICALS",
    name: "F.SAMPATH PHARMACEUTICALS",
  },
  { contact: "9585555603", companyName: "FRIENDS & CO", name: "FRIENDS & CO" },
  {
    contact: "9866014329",
    companyName: "FRIENDS FARMAA",
    name: "FRIENDS FARMAA",
  },
  {
    contact: "9150342280",
    companyName: "FRIENDS PHARMA",
    name: "FRIENDS PHARMA",
  },
  {
    contact: "9585555602",
    companyName: "FRIENDS PHARMA",
    name: "FRIENDS PHARMA",
  },
  {
    contact: "8754412411",
    companyName: "FRIENDS PHARMA",
    name: "FRIENDS PHARMA",
  },
  {
    contact: "8122842662",
    companyName: "G K MEDICAL AGENCIES",
    name: "G K MEDICAL AGENCIES",
  },
  { contact: "9943619252", companyName: "G V PHARMA", name: "G V PHARMA" },
  { contact: "9443967732", companyName: "G.R PHARMACY", name: "G.R PHARMACY" },
  { contact: "9443661057", companyName: "G.R.AGENCIES", name: "G.R.AGENCIES" },
  {
    contact: "8248795370",
    companyName: "GAJALAKSHMI PHARMA",
    name: "GAJALAKSHMI PHARMA",
  },
  {
    contact: "9842978914",
    companyName: "GAJALAKSHMI PHARMA - ERODE",
    name: "GAJALAKSHMI PHARMA - ERODE",
  },
  {
    contact: "7373018880",
    companyName: "GALAXY HEALTH CARE",
    name: "GALAXY HEALTH CARE",
  },
  {
    contact: "9942980078",
    companyName: "GALAXY PHARMA",
    name: "GALAXY PHARMA",
  },
  {
    contact: "9489543233",
    companyName: "GANAPATHI AGENCIES",
    name: "GANAPATHI AGENCIES",
  },
  {
    contact: "9080614982",
    companyName: "GANAPATHI PHARMA",
    name: "GANAPATHI PHARMA",
  },
  {
    contact: "9952788087",
    companyName: "GANAPATHY DRUG STORE",
    name: "GANAPATHY DRUG STORE",
  },
  {
    contact: "9789678456",
    companyName: "GANAPATHY MEDICAL AGENCY",
    name: "GANAPATHY MEDICAL AGENCY",
  },
  {
    contact: "9840831663",
    companyName: "GANESH PHARMA SURGICAL",
    name: "GANESH PHARMA SURGICAL",
  },
  {
    contact: "9841065987",
    companyName: "GANESH PHARMACEUTICALS",
    name: "GANESH PHARMACEUTICALS",
  },
  {
    contact: "9976609521",
    companyName: "GAYATHRI MEDICAL",
    name: "GAYATHRI MEDICAL",
  },
  {
    contact: "9655977556",
    companyName: "GEE G MEDI SYSTEM",
    name: "GEE G MEDI SYSTEM",
  },
  { contact: "9840411139", companyName: "GEETHA DRUGS", name: "GEETHA DRUGS" },
  {
    contact: "9994291119",
    companyName: "GENERAL PHARMA",
    name: "GENERAL PHARMA",
  },
  {
    contact: "9841625723",
    companyName: "GETWELL ENERPRISES",
    name: "GETWELL ENERPRISES",
  },
  {
    contact: "8098172244",
    companyName: "GLOBAL MEDI SURG",
    name: "GLOBAL MEDI SURG",
  },
  {
    contact: "9842766077",
    companyName: "GLOBAL PHARMA DISTRIBUTORS",
    name: "GLOBAL PHARMA DISTRIBUTORS",
  },
  {
    contact: "9865246664",
    companyName: "GLOBAL PHARMA DISTRIBUTORS",
    name: "GLOBAL PHARMA DISTRIBUTORS",
  },
  {
    contact: "8220661155",
    companyName: "GOKUL AGENCIES",
    name: "GOKUL AGENCIES",
  },
  {
    contact: "9894734050",
    companyName: "GOKUL AGENICES",
    name: "GOKUL AGENICES",
  },
  {
    contact: "9361046060",
    companyName: "GOLDEN PHARMA",
    name: "GOLDEN PHARMA",
  },
  {
    contact: "9443402903",
    companyName: "GOLDEN PHARMA",
    name: "GOLDEN PHARMA",
  },
  {
    contact: "9952414272",
    companyName: "GOOD LIFE PHARMA",
    name: "GOOD LIFE PHARMA",
  },
  {
    contact: "9445063041",
    companyName: "GOOD PHARMACEUTICALS",
    name: "GOOD PHARMACEUTICALS",
  },
  {
    contact: "9790793686",
    companyName: "GOWRI ENTERPRISES",
    name: "GOWRI ENTERPRISES",
  },
  {
    contact: "9443667934",
    companyName: "GUHAN PHARMA & SURGICALS",
    name: "GUHAN PHARMA & SURGICALS",
  },
  {
    contact: "9443667934",
    companyName: "GUHAN PHARMA & SURGICALS",
    name: "GUHAN PHARMA & SURGICALS",
  },
  {
    contact: "9443514879",
    companyName: "GURU AGENCIES",
    name: "GURU AGENCIES",
  },
  {
    contact: "9976004422",
    companyName: "GURU VIGENSH PHARMA",
    name: "GURU VIGENSH PHARMA",
  },
  {
    contact: "9443512566",
    companyName: "HARINI AGENCY",
    name: "HARINI AGENCY",
  },
  {
    contact: "8122249136",
    companyName: "HARISH PHARMACEUTICALS",
    name: "HARISH PHARMACEUTICALS",
  },
  {
    contact: "9940567788",
    companyName: "HARSHA ENTERPRISES",
    name: "HARSHA ENTERPRISES",
  },
  {
    contact: "9884425677",
    companyName: "HEALERS HEALTH CARE",
    name: "HEALERS HEALTH CARE",
  },
  { contact: "9790120697", companyName: "HEMA PHARMA", name: "HEMA PHARMA" },
  {
    contact: "9944030388",
    companyName: "HI TECH PHARMA",
    name: "HI TECH PHARMA",
  },
  {
    contact: "9791975366",
    companyName: "HIMALAYA PHARMA",
    name: "HIMALAYA PHARMA",
  },
  {
    contact: "9994967078",
    companyName: "HINDUSTAN TRADING CORPORATION",
    name: "HINDUSTAN TRADING CORPORATION",
  },
  {
    contact: "9442253254",
    companyName: "HI-TECH DRUGS",
    name: "HI-TECH DRUGS",
  },
  {
    contact: "7010403639",
    companyName: "HOSUR PHARMA DISTRIBUTIORS",
    name: "HOSUR PHARMA DISTRIBUTIORS",
  },
  {
    contact: "9865975377",
    companyName: "HOSUR PHARMA DISTRIBUTORS",
    name: "HOSUR PHARMA DISTRIBUTORS",
  },
  {
    contact: "9500580997",
    companyName: "HUMAN CARE PHARMACETICALS",
    name: "HUMAN CARE PHARMACETICALS",
  },
  {
    contact: "9894665500",
    companyName: "IDEAL SURGICALS",
    name: "IDEAL SURGICALS",
  },
  {
    contact: "9443126184",
    companyName: "ILANGO MEDICAL",
    name: "ILANGO MEDICAL",
  },
  { contact: "9840669500", companyName: "IMAGE BIOMED", name: "IMAGE BIOMED" },
  {
    contact: "9150742702",
    companyName: "INDIAN PHARMA",
    name: "INDIAN PHARMA",
  },
  {
    contact: "9942121983",
    companyName: "INDIAN PHARMA",
    name: "INDIAN PHARMA",
  },
  {
    contact: "9150244333",
    companyName: "INDIAN PHARMA DISTRIBUTOR",
    name: "INDIAN PHARMA DISTRIBUTOR",
  },
  {
    contact: "9150742702",
    companyName: "INDIAN PHARMA DISTRIBUTOR",
    name: "INDIAN PHARMA DISTRIBUTOR",
  },
  {
    contact: "9750488880",
    companyName: "INDIRANI MEDICAL",
    name: "INDIRANI MEDICAL",
  },
  { contact: "9943398460", companyName: "INDU TRADERS", name: "INDU TRADERS" },
  {
    contact: "9994427691",
    companyName: "J S MEDICAL AGENCY",
    name: "J S MEDICAL AGENCY",
  },
  {
    contact: "9443125216",
    companyName: "J. S. PHARMACEUTICAL DISTRIBUTORS",
    name: "J. S. PHARMACEUTICAL DISTRIBUTORS",
  },
  {
    contact: "9585606063",
    companyName: "J.K.R. PHARMA",
    name: "J.K.R. PHARMA",
  },
  { contact: "9710107659", companyName: "J.P.PHARMA", name: "J.P.PHARMA" },
  { contact: "8248911511", companyName: "J.V PHARMA", name: "J.V PHARMA" },
  {
    contact: "9489600379",
    companyName: "J2 HEALTHCASRE (OPC) PVT LTD",
    name: "J2 HEALTHCASRE (OPC) PVT LTD",
  },
  {
    contact: "8144603883",
    companyName: "JAI MARUTHI PHARMA",
    name: "JAI MARUTHI PHARMA",
  },
  {
    contact: "9884454767",
    companyName: "JAI SANTHOSH PHARMA",
    name: "JAI SANTHOSH PHARMA",
  },
  {
    contact: "6381338513",
    companyName: "JAIGANESH PHARMA",
    name: "JAIGANESH PHARMA",
  },
  {
    contact: "9842040036",
    companyName: "JAISHRI PHARMA",
    name: "JAISHRI PHARMA",
  },
  {
    contact: "9159047999",
    companyName: "JANAKI ENTERPRISES",
    name: "JANAKI ENTERPRISES",
  },
  { contact: "9965770138", companyName: "JAS PHARMA", name: "JAS PHARMA" },
  {
    contact: "9894712327",
    companyName: "JAS PHARMACEUTICALS",
    name: "JAS PHARMACEUTICALS",
  },
  {
    contact: "9443080028",
    companyName: "JAYA PHARMA AGENCIES",
    name: "JAYA PHARMA AGENCIES",
  },
  { contact: "9994946369", companyName: "JEEVA PHARMA", name: "JEEVA PHARMA" },
  {
    contact: "9629580127",
    companyName: "JEEVAN HOSPITAL SUPPLIES",
    name: "JEEVAN HOSPITAL SUPPLIES",
  },
  {
    contact: "9500854127",
    companyName: "JEEVAN PHARMACEUTICALS",
    name: "JEEVAN PHARMACEUTICALS",
  },
  {
    contact: "9994822119",
    companyName: "JEEVAN PHRMACY",
    name: "JEEVAN PHRMACY",
  },
  {
    contact: "9994833766",
    companyName: "JEEVIKA PHARMA",
    name: "JEEVIKA PHARMA",
  },
  {
    contact: "7010376776",
    companyName: "JEGANATH PHARMA",
    name: "JEGANATH PHARMA",
  },
  {
    contact: "9600668939",
    companyName: "JEYANTHI PHARMAA",
    name: "JEYANTHI PHARMAA",
  },
  {
    contact: "9884478132",
    companyName: "JK ENTERPRISES",
    name: "JK ENTERPRISES",
  },
  { contact: "9585606063", companyName: "JKR PHARMA", name: "JKR PHARMA" },
  {
    contact: "8939997717",
    companyName: "JL CITY PHARMA INDIA LTD.",
    name: "JL CITY PHARMA INDIA LTD.",
  },
  { contact: "9952793092", companyName: "JOEL PHARMA", name: "JOEL PHARMA" },
  { contact: "9842046635", companyName: "JS PHARMA", name: "JS PHARMA" },
  { contact: "9443125216", companyName: "JS PHARMA", name: "JS PHARMA" },
  {
    contact: "9994284160",
    companyName: "JUPITAR PHARMA",
    name: "JUPITAR PHARMA",
  },
  { contact: "9842173491", companyName: "K B PHARMA", name: "K B PHARMA" },
  { contact: "9789514996", companyName: "K M PHARMA", name: "K M PHARMA" },
  {
    contact: "9842160087",
    companyName: "K.S.P. PHARMA - MADURAI",
    name: "K.S.P. PHARMA - MADURAI",
  },
  { contact: "7639919738", companyName: "K.V.S PHARMA", name: "K.V.S PHARMA" },
  {
    contact: "7200044154",
    companyName: "KAMADHENAU PHARMA ",
    name: "KAMADHENAU PHARMA ",
  },
  {
    contact: "9942112821",
    companyName: "KAMALA PHARMA",
    name: "KAMALA PHARMA",
  },
  {
    contact: "7373668833",
    companyName: "KANI PHARMA&SURGICALS",
    name: "KANI PHARMA&SURGICALS",
  },
  {
    contact: "9940371750",
    companyName: "KANYAKUMARI BHAGAVATHI SURGIMED",
    name: "KANYAKUMARI BHAGAVATHI SURGIMED",
  },
  {
    contact: "9965649687/9551650275",
    companyName: "KARPAGAM PHARMA",
    name: "KARPAGAM PHARMA",
  },
  {
    contact: "9381050462",
    companyName: "KARPAGAN MEDICAL AGENCIES",
    name: "KARPAGAN MEDICAL AGENCIES",
  },
  {
    contact: "9842056483",
    companyName: "KARTHI PHARMA",
    name: "KARTHI PHARMA",
  },
  {
    contact: "7708432680",
    companyName: "KARTHICK PHARMA",
    name: "KARTHICK PHARMA",
  },
  {
    contact: "7708432680",
    companyName: "KARTHICK PHARMA",
    name: "KARTHICK PHARMA",
  },
  {
    contact: "9842141631",
    companyName: "KARTHICK PHARMA",
    name: "KARTHICK PHARMA",
  },
  {
    contact: "9841157222",
    companyName: "KARTHICK PHARMA",
    name: "KARTHICK PHARMA",
  },
  {
    contact: "9940466996",
    companyName: "KARTHIKEYAN DRUG HOUSE",
    name: "KARTHIKEYAN DRUG HOUSE",
  },
  {
    contact: "9865163051",
    companyName: "KARUNYA AGENCIES",
    name: "KARUNYA AGENCIES",
  },
  {
    contact: "8438998646",
    companyName: "KARUNYA AGENCIES",
    name: "KARUNYA AGENCIES",
  },
  {
    contact: "9952940264",
    companyName: "KASTHURI MEDICAL AGECNY",
    name: "KASTHURI MEDICAL AGECNY",
  },
  { contact: "9585688399", companyName: "KAVIN PHARMA", name: "KAVIN PHARMA" },
  {
    contact: "6381379319",
    companyName: "KAVIYA PHARMA",
    name: "KAVIYA PHARMA",
  },
  {
    contact: "9994151876",
    companyName: "KAYATHRI PHARMA",
    name: "KAYATHRI PHARMA",
  },
  {
    contact: "9751673616",
    companyName: "KEVIN PHARMA AGENCY",
    name: "KEVIN PHARMA AGENCY",
  },
  {
    contact: "9677776600",
    companyName: "KOTHAI PHARMA",
    name: "KOTHAI PHARMA",
  },
  {
    contact: "8870869132",
    companyName: "KR P AGENCIES - TRICHY",
    name: "KR P AGENCIES - TRICHY",
  },
  {
    contact: "9443264307",
    companyName: "KRISHAL DRUGS",
    name: "KRISHAL DRUGS",
  },
  {
    contact: "9443264307",
    companyName: "KRISHAL DRUGS & SURGICALS- NAGERCOI",
    name: "KRISHAL DRUGS & SURGICALS- NAGERCOI",
  },
  {
    contact: "9489119549",
    companyName: "KRISHANA MEDICINE",
    name: "KRISHANA MEDICINE",
  },
  {
    contact: "9500924674",
    companyName: "KRISHNA AGENCIES",
    name: "KRISHNA AGENCIES",
  },
  {
    contact: "9994437537",
    companyName: "KRISHNA PHARMA",
    name: "KRISHNA PHARMA",
  },
  { contact: "7339614254", companyName: "KUMAR AGENCY", name: "KUMAR AGENCY" },
  {
    contact: "9841972342",
    companyName: "KUMARAN AGENCIES - CHENNAI",
    name: "KUMARAN AGENCIES - CHENNAI",
  },
  {
    contact: "9942307595",
    companyName: "KUMARAN PHARMA",
    name: "KUMARAN PHARMA",
  },
  { contact: "7639919738", companyName: "KVS PHARMA", name: "KVS PHARMA" },
  { contact: "9489119940", companyName: "L V PHARMA", name: "L V PHARMA" },
  {
    contact: "9789361502",
    companyName: "LAKSHMI PHARMA",
    name: "LAKSHMI PHARMA",
  },
  {
    contact: "9025047147",
    companyName: "LAKSHMI PHARMA",
    name: "LAKSHMI PHARMA",
  },
  {
    contact: "9003887345",
    companyName: "LAKSHMI PHARMA - KANCHEEPURAM",
    name: "LAKSHMI PHARMA - KANCHEEPURAM",
  },
  {
    contact: "9442403699",
    companyName: "LAKSHMI PHARMA & SURGICALS",
    name: "LAKSHMI PHARMA & SURGICALS",
  },
  {
    contact: "9444697292",
    companyName: "LAKSHMI PHARMA &SURGICAL",
    name: "LAKSHMI PHARMA &SURGICAL",
  },
  {
    contact: "9150905246",
    companyName: "LEADER PHARMA",
    name: "LEADER PHARMA",
  },
  {
    contact: "8903534898",
    companyName: "LEEBANON PHARMA",
    name: "LEEBANON PHARMA",
  },
  {
    contact: "7373049611",
    companyName: "LEEOBAN  PHARMA",
    name: "LEEOBAN  PHARMA",
  },
  {
    contact: "9994447037",
    companyName: "LEKSHNA PHARMA",
    name: "LEKSHNA PHARMA",
  },
  {
    contact: "9003870188",
    companyName: "LIBRA AGENCIES",
    name: "LIBRA AGENCIES",
  },
  { contact: "9003870188", companyName: "LIBRA AGENCY", name: "LIBRA AGENCY" },
  {
    contact: "9842427186",
    companyName: "LIBRA AGENCY ",
    name: "LIBRA AGENCY ",
  },
  {
    contact: "8248817911",
    companyName: "LIFE CARE PHARMA DISTRIBUTORS",
    name: "LIFE CARE PHARMA DISTRIBUTORS",
  },
  {
    contact: "9965828777",
    companyName: "LIFE CARE PHARMACETICALS",
    name: "LIFE CARE PHARMACETICALS",
  },
  {
    contact: "9159090222",
    companyName: "LIFE CARE PHARMACETICALS",
    name: "LIFE CARE PHARMACETICALS",
  },
  {
    contact: "9159090222",
    companyName: "LIFESTYLE PHARMACETICALS",
    name: "LIFESTYLE PHARMACETICALS",
  },
  {
    contact: "9790122513",
    companyName: "LINGAM PHARMA",
    name: "LINGAM PHARMA",
  },
  { contact: "9894346284", companyName: "LK PHARMA", name: "LK PHARMA" },
  { contact: "9715271925", companyName: "LUCKY PHARMA", name: "LUCKY PHARMA" },
  { contact: "9025287450", companyName: "LUCKY PHARMA", name: "LUCKY PHARMA" },
  { contact: "9789733440", companyName: "M M PHAMRA", name: "M M PHAMRA" },
  {
    contact: "7010611147",
    companyName: "M R PHARMA AND SURGICAL",
    name: "M R PHARMA AND SURGICAL",
  },
  {
    contact: "9443491041",
    companyName: "M. D. K. DRUGS AGENCY - VELLORE",
    name: "M. D. K. DRUGS AGENCY - VELLORE",
  },
  {
    contact: "9677764508",
    companyName: "M.M MEDICAL AGENCY",
    name: "M.M MEDICAL AGENCY",
  },
  { contact: "8122845448", companyName: "M.M.PHARMA", name: "M.M.PHARMA" },
  { contact: "9360093973", companyName: "M.R PHARMA", name: "M.R PHARMA" },
  {
    contact: "9894399545",
    companyName: "MADHAN SURGICALS",
    name: "MADHAN SURGICALS",
  },
  {
    contact: "9894399545",
    companyName: "MADHAN SURGICALS ",
    name: "MADHAN SURGICALS ",
  },
  {
    contact: "9751571057",
    companyName: "MADURA AGENCIES",
    name: "MADURA AGENCIES",
  },
  {
    contact: "9629341600",
    companyName: "MADURA AGENCIES",
    name: "MADURA AGENCIES",
  },
  {
    contact: "9943264647",
    companyName: "MADURAVALLI PHARMA",
    name: "MADURAVALLI PHARMA",
  },
  {
    contact: "9443537592",
    companyName: "MAHALAKSHMI AGENCIES - CUDDALORE",
    name: "MAHALAKSHMI AGENCIES - CUDDALORE",
  },
  {
    contact: "9865221163",
    companyName: "MAHALAKSHMI MEDICAL",
    name: "MAHALAKSHMI MEDICAL",
  },
  {
    contact: "9865253007",
    companyName: "MAHALAKSHMI MEDICAL",
    name: "MAHALAKSHMI MEDICAL",
  },
  {
    contact: "7540015555",
    companyName: "MAHALAKSHMI PHARMA",
    name: "MAHALAKSHMI PHARMA",
  },
  {
    contact: "9842459761",
    companyName: "MAHARANI PHARMA",
    name: "MAHARANI PHARMA",
  },
  {
    contact: "9943364522",
    companyName: "MALAIAMMAN MEDICAL AGENCIES",
    name: "MALAIAMMAN MEDICAL AGENCIES",
  },
  {
    contact: "9443021050",
    companyName: "MALLIGAI PHARMA",
    name: "MALLIGAI PHARMA",
  },
  {
    contact: "9789620286",
    companyName: "MALLIKA AGENCIES",
    name: "MALLIKA AGENCIES",
  },
  {
    contact: "9884214645",
    companyName: "MANGAL TRADE LINK",
    name: "MANGAL TRADE LINK",
  },
  {
    contact: "9381006990",
    companyName: "MANI PHARMACEUTICALS - TIRUNELVELI",
    name: "MANI PHARMACEUTICALS - TIRUNELVELI",
  },
  {
    contact: "8148660056",
    companyName: "MANISHA PHARMA",
    name: "MANISHA PHARMA",
  },
  {
    contact: "8428487777",
    companyName: "MARUTHI ENTERPRISES",
    name: "MARUTHI ENTERPRISES",
  },
  {
    contact: "9677033549",
    companyName: "MAS HEALTHCARE",
    name: "MAS HEALTHCARE",
  },
  {
    contact: "7299988868",
    companyName: "MAYILVAHANAN PHARMACEUTICALS - CHEN",
    name: "MAYILVAHANAN PHARMACEUTICALS - CHEN",
  },
  {
    contact: "7010128767",
    companyName: "MCR MEDICAL DISTRIBUTORS",
    name: "MCR MEDICAL DISTRIBUTORS",
  },
  {
    contact: "7010128767 / 9597870981",
    companyName: "MCR MEDICAL DISTRIBUTORS",
    name: "MCR MEDICAL DISTRIBUTORS",
  },
  { contact: "9894553122", companyName: "MED FIRST", name: "MED FIRST" },
  { contact: "9445677359", companyName: "MEDI CRAFT", name: "MEDI CRAFT" },
  { contact: "9444020163", companyName: "MEDI SAGAR", name: "MEDI SAGAR" },
  {
    contact: "9751310284",
    companyName: "MEDICO TECH AEGNCY ",
    name: "MEDICO TECH AEGNCY ",
  },
  {
    contact: "9367628899",
    companyName: "MEDITEK HEALTHCARE INC",
    name: "MEDITEK HEALTHCARE INC",
  },
  {
    contact: "9444666683",
    companyName: "MEDIX PHARMACEUTICALS-CHENNAI",
    name: "MEDIX PHARMACEUTICALS-CHENNAI",
  },
  {
    contact: "9597808075",
    companyName: "MEDWIN PHARMA",
    name: "MEDWIN PHARMA",
  },
  {
    contact: "8122330246",
    companyName: "MEENA ENTERPRISES",
    name: "MEENA ENTERPRISES",
  },
  { contact: "9865771739", companyName: "MEENA PHARMA", name: "MEENA PHARMA" },
  {
    contact: "9842405790",
    companyName: "MEENAKCHI DRUG HOUSE",
    name: "MEENAKCHI DRUG HOUSE",
  },
  {
    contact: "9710728313",
    companyName: "MEENAKCHI PHARMACEUTICALS",
    name: "MEENAKCHI PHARMACEUTICALS",
  },
  {
    contact: "9442058953",
    companyName: "MEENAKSHI AGENCIES",
    name: "MEENAKSHI AGENCIES",
  },
  {
    contact: "9443569162",
    companyName: "MEENAKSHMI AGENCIES",
    name: "MEENAKSHMI AGENCIES",
  },
  {
    contact: "9751931032",
    companyName: "MELUR MEDICAL AGENCIES",
    name: "MELUR MEDICAL AGENCIES",
  },
  {
    contact: "9790487173",
    companyName: "MELUR MEDICAL AGENCIES",
    name: "MELUR MEDICAL AGENCIES",
  },
  {
    contact: "9443507776",
    companyName: "MERCURY PHARMA - SANKARANKOVIL",
    name: "MERCURY PHARMA - SANKARANKOVIL",
  },
  {
    contact: "9841652589",
    companyName: "METRO ENTERPRISES",
    name: "METRO ENTERPRISES",
  },
  { contact: "9345960679", companyName: "MG PHARMA", name: "MG PHARMA" },
  { contact: "8344121234", companyName: "MIDAS PHARMA", name: "MIDAS PHARMA" },
  {
    contact: "9487666426",
    companyName: "MLM ENTERPRISES",
    name: "MLM ENTERPRISES",
  },
  {
    contact: "9842149553",
    companyName: "MOHAN MEDICAL AGENCIES",
    name: "MOHAN MEDICAL AGENCIES",
  },
  { contact: "9443030685", companyName: "MOHAN PHARMA", name: "MOHAN PHARMA" },
  {
    contact: "9444033948",
    companyName: "MOTHI PHARMA (GENERIC) - CHENNAI",
    name: "MOTHI PHARMA (GENERIC) - CHENNAI",
  },
  {
    contact: "9094448434",
    companyName: "MS PHARMA AND DISTRIBUTORS",
    name: "MS PHARMA AND DISTRIBUTORS",
  },
  {
    contact: "9840520086",
    companyName: "MUNOT PHARMACEUTICALS",
    name: "MUNOT PHARMACEUTICALS",
  },
  {
    contact: "9944928700",
    companyName: "MURALI MOTHI PHARMA",
    name: "MURALI MOTHI PHARMA",
  },
  {
    contact: "9444894981",
    companyName: "MURALI MOTHI PHARMA",
    name: "MURALI MOTHI PHARMA",
  },
  {
    contact: "9487212639",
    companyName: "MURUGAN MEDICAL AGENCY",
    name: "MURUGAN MEDICAL AGENCY",
  },
  {
    contact: "9944574100",
    companyName: "MURUGAN PHARMA",
    name: "MURUGAN PHARMA",
  },
  {
    contact: "9940904140",
    companyName: "MURUGAPA AGENCIES",
    name: "MURUGAPA AGENCIES",
  },
  {
    contact: "9940761517",
    companyName: "MURUKAN PHARMA",
    name: "MURUKAN PHARMA",
  },
  {
    contact: "9047008980",
    companyName: "MUTHU MEENA PHARMACETICALS",
    name: "MUTHU MEENA PHARMACETICALS",
  },
  {
    contact: "7373794548",
    companyName: "MUTHU PHARMA& SURGICALS",
    name: "MUTHU PHARMA& SURGICALS",
  },
  {
    contact: "9994020111",
    companyName: "MYURA SURGICAL PHARMA",
    name: "MYURA SURGICAL PHARMA",
  },
  {
    contact: "9994020111",
    companyName: "MYURA SURGICAL PHARMA",
    name: "MYURA SURGICAL PHARMA",
  },
  {
    contact: "9894860723",
    companyName: "N T R AGENCIES",
    name: "N T R AGENCIES",
  },
  {
    contact: "9842164678",
    companyName: "NAGAPPA AGENCIES",
    name: "NAGAPPA AGENCIES",
  },
  {
    contact: "8940578027",
    companyName: "NAGU MEDICAL AGENCY",
    name: "NAGU MEDICAL AGENCY",
  },
  { contact: "9944614100", companyName: "NALAN PHARMA", name: "NALAN PHARMA" },
  {
    contact: "9442329203",
    companyName: "NANJIL PHARMA AGENCY",
    name: "NANJIL PHARMA AGENCY",
  },
  {
    contact: "9944614100",
    companyName: "NANTHINI PHARMA",
    name: "NANTHINI PHARMA",
  },
  {
    contact: "9894720007",
    companyName: "NATARAJA ENTERPRISES",
    name: "NATARAJA ENTERPRISES",
  },
  {
    contact: "9842156511",
    companyName: "NATIONAL PHARMA",
    name: "NATIONAL PHARMA",
  },
  {
    contact: "9884629692",
    companyName: "NATIONAL PHARMA  & GENERICS",
    name: "NATIONAL PHARMA  & GENERICS",
  },
  {
    contact: "9787973666",
    companyName: "NATIONAL PHARMA AGENCIES",
    name: "NATIONAL PHARMA AGENCIES",
  },
  {
    contact: "9361294465",
    companyName: "NAVAKAR PHARMA",
    name: "NAVAKAR PHARMA",
  },
  {
    contact: "9842402024",
    companyName: "NEEVI AGENCIES",
    name: "NEEVI AGENCIES",
  },
  { contact: "9842402024", companyName: "NEEVI AGENCY", name: "NEEVI AGENCY" },
  { contact: "9865799173", companyName: "NELLAI DRUGS", name: "NELLAI DRUGS" },
  {
    contact: "9884395678",
    companyName: "NETHRAS PHARMACEUTICALS",
    name: "NETHRAS PHARMACEUTICALS",
  },
  {
    contact: "8667007971",
    companyName: "NEW LIFE PHARMA",
    name: "NEW LIFE PHARMA",
  },
  {
    contact: "8807506898",
    companyName: "NEW NATIONAL PHARMA",
    name: "NEW NATIONAL PHARMA",
  },
  {
    contact: "9498624964",
    companyName: "NEW RAJ SURGICALS",
    name: "NEW RAJ SURGICALS",
  },
  {
    contact: "9788952541",
    companyName: "NEW SAKTHI MEDICAL",
    name: "NEW SAKTHI MEDICAL",
  },
  {
    contact: "9443618545",
    companyName: "NEW SKY PHARMA",
    name: "NEW SKY PHARMA",
  },
  {
    contact: "9786836649",
    companyName: "NIRMAL PHARMA",
    name: "NIRMAL PHARMA",
  },
  { contact: "9894860723", companyName: "NTR AGENCIES", name: "NTR AGENCIES" },
  {
    contact: "9486340790",
    companyName: "OEKAR PHARMA & SURGICALS - PANRUTI",
    name: "OEKAR PHARMA & SURGICALS - PANRUTI",
  },
  {
    contact: "9787303897",
    companyName: "OM SAHAKTHI PHARMA DISTRIBUTORS",
    name: "OM SAHAKTHI PHARMA DISTRIBUTORS",
  },
  {
    contact: "9894178958",
    companyName: "OM SAKTHI AGENCIES",
    name: "OM SAKTHI AGENCIES",
  },
  {
    contact: "9789440865",
    companyName: "ORANGE PHARMA & SURGICAL",
    name: "ORANGE PHARMA & SURGICAL",
  },
  {
    contact: "9566884086",
    companyName: "ORANGE PHARMA AND SURGICALS",
    name: "ORANGE PHARMA AND SURGICALS",
  },
  {
    contact: "9884242450",
    companyName: "ORGANICS PHARMACEUTICALS",
    name: "ORGANICS PHARMACEUTICALS",
  },
  { contact: "9345675290", companyName: "OSCAR PHARMA", name: "OSCAR PHARMA" },
  { contact: "9080007090", companyName: "OSCAR PHARMA", name: "OSCAR PHARMA" },
  {
    contact: "9150321006",
    companyName: "PACKIALAXMI PHARMA",
    name: "PACKIALAXMI PHARMA",
  },
  {
    contact: "9150321006",
    companyName: "PACKIALAXMI PHARMA",
    name: "PACKIALAXMI PHARMA",
  },
  {
    contact: "9884014425",
    companyName: "PADAM PHARMA DISTRIBUTOR - CHOOLAI",
    name: "PADAM PHARMA DISTRIBUTOR - CHOOLAI",
  },
  {
    contact: "9865002108",
    companyName: "PALLADAM PHARMA",
    name: "PALLADAM PHARMA",
  },
  { contact: "9841033188", companyName: "PARAS PHARMA", name: "PARAS PHARMA" },
  {
    contact: "9840040692",
    companyName: "PARSHVA PHARMA DISTRIBUTORS",
    name: "PARSHVA PHARMA DISTRIBUTORS",
  },
  {
    contact: "9884846754",
    companyName: "PEACOCK PHARMACETICALS",
    name: "PEACOCK PHARMACETICALS",
  },
  {
    contact: "9787170638",
    companyName: "PERI CURE PHARMA",
    name: "PERI CURE PHARMA",
  },
  {
    contact: "9787170638",
    companyName: "PERICURE PHARMA",
    name: "PERICURE PHARMA",
  },
  { contact: "9842576818", companyName: "PHARMA CARE ", name: "PHARMA CARE " },
  {
    contact: "9443520813",
    companyName: "PHARMA DARSHAN",
    name: "PHARMA DARSHAN",
  },
  {
    contact: "9443194070",
    companyName: "PHARMA GALAXY",
    name: "PHARMA GALAXY",
  },
  { contact: "9842110035", companyName: "PHARMA GROW", name: "PHARMA GROW" },
  {
    contact: "9444811114",
    companyName: "PHARMA TRADE ",
    name: "PHARMA TRADE ",
  },
  {
    contact: "9842797669",
    companyName: "PHARMA TRADERS ",
    name: "PHARMA TRADERS ",
  },
  {
    contact: "9710114254",
    companyName: "PHARMA UNLIMITED",
    name: "PHARMA UNLIMITED",
  },
  {
    contact: "9442363668",
    companyName: "PIONNER PHARMA",
    name: "PIONNER PHARMA",
  },
  { contact: "9677921481", companyName: "PKS PHARAMA", name: "PKS PHARAMA" },
  {
    contact: "9884178014",
    companyName: "POOJA AGENCIES",
    name: "POOJA AGENCIES",
  },
  {
    contact: "9443077994",
    companyName: "POPULAR DRUG HOSUE",
    name: "POPULAR DRUG HOSUE",
  },
  {
    contact: "9443082960",
    companyName: "PRABHA DRUG HOUSE ",
    name: "PRABHA DRUG HOUSE ",
  },
  {
    contact: "9443082960",
    companyName: "PRABHA DRUG HOUSE - HOSUR",
    name: "PRABHA DRUG HOUSE - HOSUR",
  },
  {
    contact: "9008829997",
    companyName: "PRAKASH PHARMA",
    name: "PRAKASH PHARMA",
  },
  {
    contact: "9008829997",
    companyName: "PRAKASH PHARMA",
    name: "PRAKASH PHARMA",
  },
  {
    contact: "7094341069",
    companyName: "PRATHANA MANTHRI BHARTIYA",
    name: "PRATHANA MANTHRI BHARTIYA",
  },
  {
    contact: "9789885177",
    companyName: "PRAVEEN PHARMA",
    name: "PRAVEEN PHARMA",
  },
  {
    contact: "9994959434",
    companyName: "PREETHA MEDICAL AGENCY",
    name: "PREETHA MEDICAL AGENCY",
  },
  {
    contact: "9994381700",
    companyName: "PRIME PHARMA SURGICALS - SALEM",
    name: "PRIME PHARMA SURGICALS - SALEM",
  },
  {
    contact: "9940200957",
    companyName: "PRITHIK PHARMA",
    name: "PRITHIK PHARMA",
  },
  { contact: "9940762804", companyName: "PRIYA PHARMA", name: "PRIYA PHARMA" },
  {
    contact: "9080503460",
    companyName: "PRIYAM PHARMA",
    name: "PRIYAM PHARMA",
  },
  { contact: "9585383339", companyName: "PSD PHARMA", name: "PSD PHARMA" },
  {
    contact: "9789497460",
    companyName: "PUNNIYA PHARMA",
    name: "PUNNIYA PHARMA",
  },
  {
    contact: "9944666788",
    companyName: "PUSHPA PHARMA",
    name: "PUSHPA PHARMA",
  },
  {
    contact: "9840348111",
    companyName: "PUSHPUM TRADERS ",
    name: "PUSHPUM TRADERS ",
  },
  { contact: "9884446044", companyName: "R C PHARMA ", name: "R CPHARMA " },
  {
    contact: "7395972727",
    companyName: "R R HEALTH CARE",
    name: "R R HEALTH CARE",
  },
  {
    contact: "9841059972",
    companyName: "R.S.VACCINES AND SURGICALS",
    name: "R.S.VACCINES AND SURGICALS",
  },
  {
    contact: "8072684457",
    companyName: "RADHA MEDICAL AGENCY",
    name: "RADHA MEDICAL AGENCY",
  },
  { contact: "8610495914", companyName: "RADHA PHARMA", name: "RADHA PHARMA" },
  {
    contact: "9443487174",
    companyName: "RAGHU SURGICAL",
    name: "RAGHU SURGICAL",
  },
  { contact: "9443345113", companyName: "RAJ PHARMA", name: "RAJ PHARMA" },
  {
    contact: "9443375163",
    companyName: "RAJ PHARMACEUTICALS - MADURAI",
    name: "RAJ PHARMACEUTICALS - MADURAI",
  },
  {
    contact: "9600745085",
    companyName: "RAJ SURGICALS ",
    name: "RAJ SURGICALS ",
  },
  {
    contact: "8012073917",
    companyName: "RAJA MEDICAL CORPORATION",
    name: "RAJA MEDICAL CORPORATION",
  },
  {
    contact: "9080548278",
    companyName: "RAJA PHARMA AGENCY",
    name: "RAJA PHARMA AGENCY",
  },
  {
    contact: "9843163387",
    companyName: "RAJAMANI ENTERPRISES",
    name: "RAJAMANI ENTERPRISES",
  },
  {
    contact: "9443542360",
    companyName: "RAJESHWAR PHARMA",
    name: "RAJESHWAR PHARMA",
  },
  {
    contact: "9865438251",
    companyName: "RAJINI PHARMA",
    name: "RAJINI PHARMA",
  },
  {
    contact: "9976080300",
    companyName: "RAKSHAN PHARMA",
    name: "RAKSHAN PHARMA",
  },
  { contact: "9976731313", companyName: "RAM PHARMA", name: "RAM PHARMA" },
  {
    contact: "9894287516",
    companyName: "RAMACHANDRA PHARMA",
    name: "RAMACHANDRA PHARMA",
  },
  {
    contact: "7904692015",
    companyName: "RAMANA PHARMA",
    name: "RAMANA PHARMA",
  },
  {
    contact: "9842783010",
    companyName: "RAMANY PHARMA",
    name: "RAMANY PHARMA",
  },
  {
    contact: "9994939888",
    companyName: "RAMLAKSHMAN AGENCIES",
    name: "RAMLAKSHMAN AGENCIES",
  },
  {
    contact: "9841736266",
    companyName: "RAMSON MEDICAL DISTRIBUTORS",
    name: "RAMSON MEDICAL DISTRIBUTORS",
  },
  {
    contact: "8939889880",
    companyName: "RAMSON MEDICAL DISTRIBUTORS",
    name: "RAMSON MEDICAL DISTRIBUTORS",
  },
  {
    contact: "9840504440",
    companyName: "RAMSON MEDICAL DISTRIBUTORS (P",
    name: "RAMSON MEDICAL DISTRIBUTORS (P",
  },
  {
    contact: "9790953563",
    companyName: "RAMSON MEDICAL DISTRIBUTORS PVT LTD",
    name: "RAMSON MEDICAL DISTRIBUTORS PVT LTD",
  },
  {
    contact: "9790895396",
    companyName: "RAMSON MEDICAL DISTRIBUTORS PVT LTD",
    name: "RAMSON MEDICAL DISTRIBUTORS PVT LTD",
  },
  {
    contact: "9790953562",
    companyName: "RAMSON MEDICAL DISTRIBUTORS PVT. LTD.",
    name: "RAMSON MEDICAL DISTRIBUTORS PVT. LTD.",
  },
  {
    contact: "9790953564",
    companyName: "RAMSON PHARMA",
    name: "RAMSON PHARMA",
  },
  {
    contact: "9500073183",
    companyName: "RAMSON PHARMA",
    name: "RAMSON PHARMA",
  },
  {
    contact: "9080171367",
    companyName: "RAMSON PHARMA",
    name: "RAMSON PHARMA",
  },
  {
    contact: "9884011188",
    companyName: "RAMSON PHARMA DISTRIBUTORS",
    name: "RAMSON PHARMA DISTRIBUTORS",
  },
  {
    contact: "9884016310",
    companyName: "RAMSON PHARMA DISTRIBUTORS",
    name: "RAMSON PHARMA DISTRIBUTORS",
  },
  {
    contact: "9942905271",
    companyName: "RAMU ENTERPRISES",
    name: "RAMU ENTERPRISES",
  },
  {
    contact: "9489139555",
    companyName: "RAMVEL PHARMA",
    name: "RAMVEL PHARMA",
  },
  {
    contact: "9489139555",
    companyName: "RAMVEL PHARMA",
    name: "RAMVEL PHARMA",
  },
  {
    contact: "9647678084",
    companyName: "RB PHARMA DISTRIBUTORS",
    name: "RB PHARMA DISTRIBUTORS",
  },
  {
    contact: "9647678084",
    companyName: "RB PHARMA DISTRIBUTORS",
    name: "RB PHARMA DISTRIBUTORS",
  },
  {
    contact: "9865076751",
    companyName: "RECEIPE PHARMA",
    name: "RECEIPE PHARMA",
  },
  {
    contact: "9865076751",
    companyName: "RECIEPE PHARMA",
    name: "RECIEPE PHARMA",
  },
  {
    contact: "9894307677",
    companyName: "RED GAINT PHARMA",
    name: "RED GAINT PHARMA",
  },
  {
    contact: "7010569683",
    companyName: "REDMED PHARMA & SURGICALS",
    name: "REDMED PHARMA & SURGICALS",
  },
  {
    contact: "9788117987",
    companyName: "REXTAN PHARMA",
    name: "REXTAN PHARMA",
  },
  { contact: "9965542718", companyName: "RIFA AGENCY", name: "RIFA AGENCY" },
  { contact: "9442163786", companyName: "RISHI PHARMA", name: "RISHI PHARMA" },
  { contact: "9442163786", companyName: "RISHI PHARMA", name: "RISHI PHARMA" },
  {
    contact: "9025599760",
    companyName: "RJL ANNAI PHARMA",
    name: "RJL ANNAI PHARMA",
  },
  { contact: "9941319275", companyName: "RK SURGICALS", name: "RK SURGICALS" },
  {
    contact: "9994011989",
    companyName: "ROBUST PHARMA",
    name: "ROBUST PHARMA",
  },
  { contact: "9940395547", companyName: "ROYAL PHARMA", name: "ROYAL PHARMA" },
  { contact: "9940395547", companyName: "ROYAL PHARMA", name: "ROYAL PHARMA" },
  { contact: "7010439559", companyName: "S D K PHARMA", name: "S D K PHARMA" },
  { contact: "9940869343", companyName: "S M AGENCY", name: "S M AGENCY" },
  { contact: "9788823838", companyName: "S M PHARMA ", name: "S M PHARMA " },
  {
    contact: "9486555065",
    companyName: "S P M MEDICAL MART",
    name: "S P M MEDICAL MART",
  },
  {
    contact: "9092830110",
    companyName: "S R PHARMACETICALS",
    name: "S R PHARMACETICALS",
  },
  { contact: "9790033783", companyName: "S S PHARMA", name: "S S PHARMA" },
  { contact: "9965482550", companyName: "S S PHARMA", name: "S S PHARMA" },
  { contact: "9787815136", companyName: "S S PHARMA", name: "S S PHARMA" },
  { contact: "9790033783", companyName: "S S PHARMA", name: "S S PHARMA" },
  {
    contact: "9715420778",
    companyName: "S.D.K. PHARMA",
    name: "S.D.K. PHARMA",
  },
  { contact: "9940559489", companyName: "S.K AGENCY", name: "S.K AGENCY" },
  { contact: "9345546937", companyName: "S.P PHARMA", name: "S.P PHARMA" },
  {
    contact: "9865557957",
    companyName: "S.P. AGENCIES",
    name: "S.P. AGENCIES",
  },
  {
    contact: "9839439735",
    companyName: "S.P. AGENCIES - KALLAKURICHI",
    name: "S.P. AGENCIES - KALLAKURICHI",
  },
  {
    contact: "9159770795",
    companyName: "S.P.L PHARMA &MEDICALS",
    name: "S.P.L PHARMA &MEDICALS",
  },
  {
    contact: "8754715649",
    companyName: "S.P.SURGICALS",
    name: "S.P.SURGICALS",
  },
  {
    contact: "9790033783",
    companyName: "S.S MEDICAL AGENCY",
    name: "S.S MEDICAL AGENCY",
  },
  { contact: "8667399906", companyName: "S.S PHARMA", name: "S.S PHARMA" },
  { contact: "7358806969", companyName: "S.S PHARMA", name: "S.S PHARMA" },
  { contact: "9840843252", companyName: "S.V.PHARMA", name: "S.V.PHARMA" },
  { contact: "8903050627", companyName: "S.V.R PHARMA", name: "S.V.R PHARMA" },
  {
    contact: "9842308991",
    companyName: "S.V.R. PHARMA",
    name: "S.V.R. PHARMA",
  },
  {
    contact: "9442566474",
    companyName: "SAAI GIRI AGENCIES",
    name: "SAAI GIRI AGENCIES",
  },
  {
    contact: "9842164873",
    companyName: "SABHARISH PHARMA",
    name: "SABHARISH PHARMA",
  },
  {
    contact: "9842727390",
    companyName: "SAGAR PHARMA &GENERICS",
    name: "SAGAR PHARMA &GENERICS",
  },
  { contact: "9345208004", companyName: "SAHAM AGENCY", name: "SAHAM AGENCY" },
  {
    contact: "9443564483",
    companyName: "SAHARA PHARMA SURGICALS",
    name: "SAHARA PHARMA SURGICALS",
  },
  {
    contact: "9367430404",
    companyName: "SAI KIRUPA AGENCIES",
    name: "SAI KIRUPA AGENCIES",
  },
  {
    contact: "9443227178",
    companyName: "SAI RAM PHARMA",
    name: "SAI RAM PHARMA",
  },
  {
    contact: "9952455701",
    companyName: "SAI VELAN PHARMA",
    name: "SAI VELAN PHARMA",
  },
  {
    contact: "7373779119",
    companyName: "SAI VENKATESH AGENCY",
    name: "SAI VENKATESH AGENCY",
  },
  {
    contact: "7373779116",
    companyName: "SAI VENKATESH AGENCYT",
    name: "SAI VENKATESH AGENCYT",
  },
  {
    contact: "9025430404",
    companyName: "SAIKRUPA PHARMACEUTICALS",
    name: "SAIKRUPA PHARMACEUTICALS",
  },
  {
    contact: "9443405805",
    companyName: "SAJEE MEDICAL",
    name: "SAJEE MEDICAL",
  },
  {
    contact: "9842280985",
    companyName: "SAKTHI AGENCIES-COIMBATORE",
    name: "SAKTHI AGENCIES-COIMBATORE",
  },
  {
    contact: "7824934120",
    companyName: "SAKTHI MEDICAL AGENCY",
    name: "SAKTHI MEDICAL AGENCY",
  },
  {
    contact: "9994950994",
    companyName: "SAKTHI PHARMA",
    name: "SAKTHI PHARMA",
  },
  {
    contact: "9443872724",
    companyName: "SAKTHI PHARMA",
    name: "SAKTHI PHARMA",
  },
  {
    contact: "9994950994",
    companyName: "SAKTHI PHARMACEUTICALS",
    name: "SAKTHI PHARMACEUTICALS",
  },
  {
    contact: "7010809052",
    companyName: "SAKTHI PHARMACEUTICALS",
    name: "SAKTHI PHARMACEUTICALS",
  },
  { contact: "6383732065", companyName: "SALEM PHARMA", name: "SALEM PHARMA" },
  { contact: "9787320871", companyName: "SALMA PHARMA", name: "SALMA PHARMA" },
  {
    contact: "9786088291",
    companyName: "SAMY MEDICAL AGENCY",
    name: "SAMY MEDICAL AGENCY",
  },
  {
    contact: "9585701425",
    companyName: "SANA MEDICAL DISTRIBUTOR",
    name: "SANA MEDICAL DISTRIBUTOR",
  },
  {
    contact: "9500000827",
    companyName: "SANDEEP PHARMA",
    name: "SANDEEP PHARMA",
  },
  {
    contact: "9840817027",
    companyName: "SANDEEP PHARMA",
    name: "SANDEEP PHARMA",
  },
  {
    contact: "9788856266",
    companyName: "SANKAR PHARMA - SIVAKASI",
    name: "SANKAR PHARMA - SIVAKASI",
  },
  {
    contact: "6382173646",
    companyName: "SANKAR PHARMA SURGICALSS",
    name: "SANKAR PHARMA SURGICALSS",
  },
  {
    contact: "8489928475",
    companyName: "SARASWATHI AGENCIES - VILLUPURAM",
    name: "SARASWATHI AGENCIES - VILLUPURAM",
  },
  {
    contact: "8015225512",
    companyName: "SARAVANA PHARMA",
    name: "SARAVANA PHARMA",
  },
  {
    contact: "9994945443",
    companyName: "SARAVANA PHARMA",
    name: "SARAVANA PHARMA",
  },
  {
    contact: "7639578630",
    companyName: "SARAVANAN PHARMA",
    name: "SARAVANAN PHARMA",
  },
  {
    contact: "9940893319",
    companyName: "SARGURU PHARMA",
    name: "SARGURU PHARMA",
  },
  {
    contact: "9841862293",
    companyName: "SATHYA PHARMA",
    name: "SATHYA PHARMA",
  },
  {
    contact: "9841862293",
    companyName: "SATHYA PHARMA",
    name: "SATHYA PHARMA",
  },
  {
    contact: "9787066244",
    companyName: "SELVAM PHARMA",
    name: "SELVAM PHARMA",
  },
  {
    contact: "8883340250",
    companyName: "SENTHIL AGENCIES",
    name: "SENTHIL AGENCIES",
  },
  {
    contact: "9597749299",
    companyName: "SENTHIL AGENIECS",
    name: "SENTHIL AGENIECS",
  },
  {
    contact: "9677840852",
    companyName: "SENTHIL ANDAVAR AGENCY",
    name: "SENTHIL ANDAVAR AGENCY",
  },
  {
    contact: "9865028111",
    companyName: "SENTHIL PHARMA ",
    name: "SENTHIL PHARMA ",
  },
  {
    contact: "9952806492",
    companyName: "SENTHILNATHAN PHARMA",
    name: "SENTHILNATHAN PHARMA",
  },
  {
    contact: "9940490490",
    companyName: "SEYON PHARMACEUTICALS",
    name: "SEYON PHARMACEUTICALS",
  },
  {
    contact: "9500946644",
    companyName: "SHALIMAR DISTRIBUTORS - ERODE",
    name: "SHALIMAR DISTRIBUTORS - ERODE",
  },
  {
    contact: "9884401983",
    companyName: "SHANGEETH DRUGS",
    name: "SHANGEETH DRUGS",
  },
  {
    contact: "9842990009",
    companyName: "SHANKAR PHARMA SURGICALSS",
    name: "SHANKAR PHARMA SURGICALSS",
  },
  {
    contact: "9095225888",
    companyName: "SHIFA PHARMA SURGICALS",
    name: "SHIFA PHARMA SURGICALS",
  },
  {
    contact: "9443112277",
    companyName: "SHIVALAYA PHARMA",
    name: "SHIVALAYA PHARMA",
  },
  {
    contact: "8667712938",
    companyName: "SHRE SARAVANA MEDICAL AGENCY",
    name: "SHRE SARAVANA MEDICAL AGENCY",
  },
  {
    contact: "9840635994",
    companyName: "SHREE DARSHAN PHARMA",
    name: "SHREE DARSHAN PHARMA",
  },
  {
    contact: "9840990771",
    companyName: "SHREE DARSHAN PHARMA - CHENNAI",
    name: "SHREE DARSHAN PHARMA - CHENNAI",
  },
  {
    contact: "9626802952",
    companyName: "SHREE DHANVANTHRI PHARMA",
    name: "SHREE DHANVANTHRI PHARMA",
  },
  {
    contact: "9962083600",
    companyName: "SHREE GENERICS",
    name: "SHREE GENERICS",
  },
  {
    contact: "9094666695",
    companyName: "SHREE PHARMA DISTRIBUTORS",
    name: "SHREE PHARMA DISTRIBUTORS",
  },
  {
    contact: "9150492949",
    companyName: "SHREE VARAM AGENCIES",
    name: "SHREE VARAM AGENCIES",
  },
  {
    contact: "9585238238",
    companyName: "SHREE VIJAY PHARMA",
    name: "SHREE VIJAY PHARMA",
  },
  {
    contact: "9994611226",
    companyName: "SHRI AMBIGAI PHARMA & SURGICAL",
    name: "SHRI AMBIGAI PHARMA & SURGICAL",
  },
  {
    contact: "9994611223",
    companyName: "SHRI AMBIGAI PHARMA&SURGICALS",
    name: "SHRI AMBIGAI PHARMA&SURGICALS",
  },
  {
    contact: "9345655585",
    companyName: "SHRI BALAGI PHARMA",
    name: "SHRI BALAGI PHARMA",
  },
  {
    contact: "9442864887",
    companyName: "SHRI KURINJI PHARMA",
    name: "SHRI KURINJI PHARMA",
  },
  { contact: "9715583888", companyName: "SHRI PHARMA", name: "SHRI PHARMA" },
  {
    contact: "9940360649",
    companyName: "SHRI RAM MEDICAL AGENCIES",
    name: "SHRI RAM MEDICAL AGENCIES",
  },
  {
    contact: "9884162353",
    companyName: "SHRI RAM PHARMA",
    name: "SHRI RAM PHARMA",
  },
  {
    contact: "9655033017",
    companyName: "SHRI SWAMY MEDICAL AGENCY",
    name: "SHRI SWAMY MEDICAL AGENCY",
  },
  {
    contact: "9894794266",
    companyName: "SHRI THIRUMALAI AGENCIES",
    name: "SHRI THIRUMALAI AGENCIES",
  },
  {
    contact: "9751310284",
    companyName: "SHRIE SAMAYAPRATHAL",
    name: "SHRIE SAMAYAPRATHAL",
  },
  {
    contact: "9884322800",
    companyName: "SHUBH PHARMA DISTRIBUTORS - CHENNAI",
    name: "SHUBH PHARMA DISTRIBUTORS - CHENNAI",
  },
  {
    contact: "7530050053",
    companyName: "SIVA AGENCIES",
    name: "SIVA AGENCIES",
  },
  { contact: "9942911493", companyName: "SIVA PHARMA", name: "SIVA PHARMA" },
  {
    contact: "9942904546",
    companyName: "SIVA PHARMA - PUDUKKOTTAI",
    name: "SIVA PHARMA - PUDUKKOTTAI",
  },
  {
    contact: "9688104397",
    companyName: "SIVA SAKTHI PHARMA",
    name: "SIVA SAKTHI PHARMA",
  },
  {
    contact: "9994161123",
    companyName: "SIVAGAMI PHARMA",
    name: "SIVAGAMI PHARMA",
  },
  {
    contact: "7502836330",
    companyName: "SIVASAKTHI AGENCY",
    name: "SIVASAKTHI AGENCY",
  },
  { contact: "9443882236", companyName: "SKD PHARMA", name: "SKD PHARMA" },
  { contact: "9789456388", companyName: "SKG PHARMA", name: "SKG PHARMA" },
  {
    contact: "9543220304",
    companyName: "SKY PHARMA-CHENNAI",
    name: "SKY PHARMA-CHENNAI",
  },
  { contact: "9940869343", companyName: "SM AGENCIES", name: "SM AGENCIES" },
  {
    contact: "8012510099",
    companyName: "SOURNA LAKSHMI MEDICAL AGENCY",
    name: "SOURNA LAKSHMI MEDICAL AGENCY",
  },
  {
    contact: "8012510099",
    companyName: "SOURNALAKSHMI PHARMA",
    name: "SOURNALAKSHMI PHARMA",
  },
  {
    contact: "9787776670",
    companyName: "SOUTH INDIA PHARAMACEUTICALS-",
    name: "SOUTH INDIA PHARAMACEUTICALS-",
  },
  {
    contact: "9486351081",
    companyName: "SOWBAIYA AGENCIES",
    name: "SOWBAIYA AGENCIES",
  },
  {
    contact: "9952478971",
    companyName: "SOWMIYA PHARMA SURGICALS",
    name: "SOWMIYA PHARMA SURGICALS",
  },
  {
    contact: "9970727271 / 9655597271",
    companyName: "SOWMIYA PHARMA SURGICALS- SALEM",
    name: "SOWMIYA PHARMA SURGICALS- SALEM",
  },
  {
    contact: "9442546608",
    companyName: "SPADIX PHARMACEUTICALS",
    name: "SPADIX PHARMACEUTICALS",
  },
  { contact: "9715857382", companyName: "SPK PHARMA", name: "SPK PHARMA" },
  {
    contact: "9942209222",
    companyName: "SRE SAIRAM MEDCIAL AGENCIES",
    name: "SRE SAIRAM MEDCIAL AGENCIES",
  },
  {
    contact: "9994964333",
    companyName: "SRE SARAVANA MEDICAL AGENCIES",
    name: "SRE SARAVANA MEDICAL AGENCIES",
  },
  {
    contact: "9994914383",
    companyName: "SRE SIVAM PHARMA",
    name: "SRE SIVAM PHARMA",
  },
  {
    contact: "9994553777",
    companyName: "SREE AMMAN PHARMA AGENCY",
    name: "SREE AMMAN PHARMA AGENCY",
  },
  {
    contact: "8072070613",
    companyName: "SREE ANDAL AGENCIES",
    name: "SREE ANDAL AGENCIES",
  },
  {
    contact: "8220192606",
    companyName: "SREE ANDAL AGENCIES",
    name: "SREE ANDAL AGENCIES",
  },
  {
    contact: "9976847300",
    companyName: "SREE ARUNACHALA MEDICAL AGENCI",
    name: "SREE ARUNACHALA MEDICAL AGENCI",
  },
  {
    contact: "9994951516",
    companyName: "SREE BALAJI SUGICALS",
    name: "SREE BALAJI SUGICALS",
  },
  {
    contact: "9486371868",
    companyName: "SREE MARUTHI PHARMA AGENCIES",
    name: "SREE MARUTHI PHARMA AGENCIES",
  },
  {
    contact: "9865657314",
    companyName: "SREE MURUGAN PHARMACY",
    name: "SREE MURUGAN PHARMACY",
  },
  {
    contact: "7010114198",
    companyName: "SREE MURUGU PHARMACY",
    name: "SREE MURUGU PHARMACY",
  },
  {
    contact: "9865657314",
    companyName: "SREE MURUGU PHARMACY",
    name: "SREE MURUGU PHARMACY",
  },
  {
    contact: "8667561226",
    companyName: "SREE PHARMA DISTRIBUTORS",
    name: "SREE PHARMA DISTRIBUTORS",
  },
  {
    contact: "9840309245",
    companyName: "SREE PHARMA KINGS",
    name: "SREE PHARMA KINGS",
  },
  {
    contact: "9443328837",
    companyName: "SREE RASI PHARMA AGENCIES",
    name: "SREE RASI PHARMA AGENCIES",
  },
  {
    contact: "9487528837",
    companyName: "SREE RASI PHARMA AGENCIES",
    name: "SREE RASI PHARMA AGENCIES",
  },
  {
    contact: "7705806880",
    companyName: "SREE SAI PHARMA",
    name: "SREE SAI PHARMA",
  },
  {
    contact: "7708506880",
    companyName: "SREE SAI PHARMA",
    name: "SREE SAI PHARMA",
  },
  {
    contact: "9842032918",
    companyName: "SREE SARASWATHI MEDICAL AGENCIES",
    name: "SREE SARASWATHI MEDICAL AGENCIES",
  },
  {
    contact: "9994967817",
    companyName: "SREE SASTHA MEDICAL AGECIES",
    name: "SREE SASTHA MEDICAL AGECIES",
  },
  {
    contact: "9442882302",
    companyName: "SREE SINDHU ENTERPRISES",
    name: "SREE SINDHU ENTERPRISES",
  },
  {
    contact: "6380193992",
    companyName: "SRI ABIRAMI PHARMA",
    name: "SRI ABIRAMI PHARMA",
  },
  {
    contact: "9884227761",
    companyName: "SRI ADINATH GENERICS",
    name: "SRI ADINATH GENERICS",
  },
  {
    contact: "9047087036",
    companyName: "SRI AKSHAYA AGENCIES",
    name: "SRI AKSHAYA AGENCIES",
  },
  {
    contact: "9524973034",
    companyName: "SRI AMBAL AGENCIES",
    name: "SRI AMBAL AGENCIES",
  },
  {
    contact: "9566643678",
    companyName: "SRI AMBAL MEDICAL",
    name: "SRI AMBAL MEDICAL",
  },
  {
    contact: "9345523631",
    companyName: "SRI AMBALPHARMA",
    name: "SRI AMBALPHARMA",
  },
  {
    contact: "9750971007",
    companyName: "SRI AMMAN ENTERPRISES - TIRUVARUR",
    name: "SRI AMMAN ENTERPRISES - TIRUVARUR",
  },
  {
    contact: "9865376636",
    companyName: "SRI AMMAN MEDICAL AGRNCIES",
    name: "SRI AMMAN MEDICAL AGRNCIES",
  },
  {
    contact: "9865710840",
    companyName: "SRI AMMAN PHARMA",
    name: "SRI AMMAN PHARMA",
  },
  {
    contact: "9626334340",
    companyName: "SRI AMMAN PHARMA",
    name: "SRI AMMAN PHARMA",
  },
  {
    contact: "6381510119",
    companyName: "SRI AMMAN PHARMA",
    name: "SRI AMMAN PHARMA",
  },
  {
    contact: "9976853777",
    companyName: "SRI AMMAN PHARMACETICALS ",
    name: "SRI AMMAN PHARMACETICALS ",
  },
  {
    contact: "9443867932",
    companyName: "SRI AMMAN PHARMACY",
    name: "SRI AMMAN PHARMACY",
  },
  {
    contact: "9344454603",
    companyName: "SRI AMMAN TRADERS",
    name: "SRI AMMAN TRADERS",
  },
  {
    contact: "9884578014",
    companyName: "SRI ANANDA SURGICAL",
    name: "SRI ANANDA SURGICAL",
  },
  {
    contact: "9655535111",
    companyName: "SRI ANDAL MEDICAL",
    name: "SRI ANDAL MEDICAL",
  },
  {
    contact: "9840054896",
    companyName: "SRI ANNAI PHARMA",
    name: "SRI ANNAI PHARMA",
  },
  {
    contact: "9887607564",
    companyName: "SRI ANNAMALAI SURGICAL&PHARMA",
    name: "SRI ANNAMALAI SURGICAL&PHARMA",
  },
  {
    contact: "7904774433",
    companyName: "SRI ANNAPOORANI AGENCY",
    name: "SRI ANNAPOORANI AGENCY",
  },
  {
    contact: "9842011940",
    companyName: "SRI ANUSHA AGENCIES",
    name: "SRI ANUSHA AGENCIES",
  },
  {
    contact: "9976847300",
    companyName: "SRI ARUNACHALAM PHARMA",
    name: "SRI ARUNACHALAM PHARMA",
  },
  {
    contact: "9443873639",
    companyName: "SRI BALAJI AGENCY",
    name: "SRI BALAJI AGENCY",
  },
  {
    contact: "8608893499",
    companyName: "SRI BALAJI MEDCIAL AGENCIES",
    name: "SRI BALAJI MEDCIAL AGENCIES",
  },
  {
    contact: "8925253023",
    companyName: "SRI BALAJI MEDICAL AGENCIES",
    name: "SRI BALAJI MEDICAL AGENCIES",
  },
  {
    contact: "8608893499",
    companyName: "SRI BALAJI MEDICAL AGENCIES",
    name: "SRI BALAJI MEDICAL AGENCIES",
  },
  {
    contact: "9123526266",
    companyName: "SRI BALAJI PHARMA",
    name: "SRI BALAJI PHARMA",
  },
  {
    contact: "9443963438",
    companyName: "SRI BALAJI PHARMA SURGICALS",
    name: "SRI BALAJI PHARMA SURGICALS",
  },
  {
    contact: "9865993467",
    companyName: "SRI BOOPATHI PHARMA",
    name: "SRI BOOPATHI PHARMA",
  },
  {
    contact: "9655726009",
    companyName: "SRI DEVI PHARMACETICALS",
    name: "SRI DEVI PHARMACETICALS",
  },
  {
    contact: "9790373926",
    companyName: "SRI DHAKSHAN PHARMA",
    name: "SRI DHAKSHAN PHARMA",
  },
  {
    contact: "9790373926",
    companyName: "SRI DHAKSHAN PHARMA",
    name: "SRI DHAKSHAN PHARMA",
  },
  {
    contact: "9442643119",
    companyName: "SRI DHANALAKSHMI AGENCIES - RASIPUR",
    name: "SRI DHANALAKSHMI AGENCIES - RASIPUR",
  },
  {
    contact: "9944779635",
    companyName: "SRI DHARANI AGENCY",
    name: "SRI DHARANI AGENCY",
  },
  {
    contact: "7010212248",
    companyName: "SRI DURGA PHARMA",
    name: "SRI DURGA PHARMA",
  },
  {
    contact: "9443697687",
    companyName: "SRI HARI MEDICAL AGECNCY",
    name: "SRI HARI MEDICAL AGECNCY",
  },
  {
    contact: "9786717855",
    companyName: "SRI HARI PHARMA",
    name: "SRI HARI PHARMA",
  },
  {
    contact: "9944928700",
    companyName: "SRI HARIHARAN PHARMA",
    name: "SRI HARIHARAN PHARMA",
  },
  {
    contact: "9965129267",
    companyName: "SRI HINDUSTAN MEDICAL AGENCIES",
    name: "SRI HINDUSTAN MEDICAL AGENCIES",
  },
  {
    contact: "9443737839",
    companyName: "SRI JAIGANESH AGENCIES",
    name: "SRI JAIGANESH AGENCIES",
  },
  {
    contact: "9940083203",
    companyName: "SRI JAWAHAR PHARMA",
    name: "SRI JAWAHAR PHARMA",
  },
  {
    contact: "9940083203",
    companyName: "SRI JAWAHAR PHARMA DISTRIBUTORS",
    name: "SRI JAWAHAR PHARMA DISTRIBUTORS",
  },
  {
    contact: "9842121262",
    companyName: "SRI JEYARAMAN PHARMACEUTICALS",
    name: "SRI JEYARAMAN PHARMACEUTICALS",
  },
  {
    contact: "8489878791",
    companyName: "SRI KALISHWAR PHARMA",
    name: "SRI KALISHWAR PHARMA",
  },
  {
    contact: "9843424699",
    companyName: "SRI KANNATHAL PHARMA",
    name: "SRI KANNATHAL PHARMA",
  },
  {
    contact: "9865432443",
    companyName: "SRI KARPAGA VINAYAGA AGENCY",
    name: "SRI KARPAGA VINAYAGA AGENCY",
  },
  {
    contact: "9472167351",
    companyName: "SRI KRISHA SURGICAL & PHARMA",
    name: "SRI KRISHA SURGICAL & PHARMA",
  },
  {
    contact: "9489119549",
    companyName: "SRI KRISHNA MEDICINE",
    name: "SRI KRISHNA MEDICINE",
  },
  {
    contact: "7010748260",
    companyName: "SRI KRISHNA PHARMA",
    name: "SRI KRISHNA PHARMA",
  },
  {
    contact: "6379787722",
    companyName: "SRI KUMARAN AGENCY",
    name: "SRI KUMARAN AGENCY",
  },
  {
    contact: "9443243302",
    companyName: "SRI LAKSHMI AGENCIES",
    name: "SRI LAKSHMI AGENCIES",
  },
  {
    contact: "8870456920",
    companyName: "SRI LAKSHMI AGENCIES",
    name: "SRI LAKSHMI AGENCIES",
  },
  {
    contact: "8667862561",
    companyName: "SRI LAKSHMI AGENCIES",
    name: "SRI LAKSHMI AGENCIES",
  },
  {
    contact: "9677098749",
    companyName: "SRI LAKSHMI AGENCY",
    name: "SRI LAKSHMI AGENCY",
  },
  {
    contact: "9443262738",
    companyName: "SRI MAHALAKSHMI PHARMA",
    name: "SRI MAHALAKSHMI PHARMA",
  },
  {
    contact: "9659733741",
    companyName: "SRI MAHALAKSHMI PHARMA",
    name: "SRI MAHALAKSHMI PHARMA",
  },
  {
    contact: "9080374577",
    companyName: "SRI MALAIYAAN PHARMA",
    name: "SRI MALAIYAAN PHARMA",
  },
  {
    contact: "9884753213",
    companyName: "SRI MALAIYAAN PHARMA",
    name: "SRI MALAIYAAN PHARMA",
  },
  {
    contact: "9080374577",
    companyName: "SRI MALAIYAAN PHARMA",
    name: "SRI MALAIYAAN PHARMA",
  },
  {
    contact: "9840133381",
    companyName: "SRI MARUTHI AGENCY",
    name: "SRI MARUTHI AGENCY",
  },
  {
    contact: "9994433770",
    companyName: "SRI MARUTHI PHARMA",
    name: "SRI MARUTHI PHARMA",
  },
  {
    contact: "9994500338",
    companyName: "SRI MEENAKCHI PHARMA",
    name: "SRI MEENAKCHI PHARMA",
  },
  {
    contact: "9551441393",
    companyName: "SRI MEENAKCHI PHARMA",
    name: "SRI MEENAKCHI PHARMA",
  },
  {
    contact: "9994500338",
    companyName: "SRI MEENATCHI PHARMA",
    name: "SRI MEENATCHI PHARMA",
  },
  {
    contact: "9944574100",
    companyName: "SRI MURGAN PHARMACEUTICALS",
    name: "SRI MURGAN PHARMACEUTICALS",
  },
  {
    contact: "9585366877",
    companyName: "SRI MURUGAN PHARMA",
    name: "SRI MURUGAN PHARMA",
  },
  {
    contact: "8754205599",
    companyName: "SRI NALLU PHARMA",
    name: "SRI NALLU PHARMA",
  },
  {
    contact: "9843198241",
    companyName: "SRI PADMA TRADER",
    name: "SRI PADMA TRADER",
  },
  {
    contact: "8903548379",
    companyName: "SRI PARVATHI PHARMA",
    name: "SRI PARVATHI PHARMA",
  },
  {
    contact: "8190962576",
    companyName: "SRI PARVATHI PHARMA",
    name: "SRI PARVATHI PHARMA",
  },
  { contact: "9790990989", companyName: "SRI PHARMA", name: "SRI PHARMA" },
  {
    contact: "8680016900",
    companyName: "SRI PRIYA PHARMA",
    name: "SRI PRIYA PHARMA",
  },
  {
    contact: "9043742039",
    companyName: "SRI RAGAVENDRA AGENCIES",
    name: "SRI RAGAVENDRA AGENCIES",
  },
  {
    contact: "9884271625",
    companyName: "SRI RAGHAVANDRA DRUGS",
    name: "SRI RAGHAVANDRA DRUGS",
  },
  {
    contact: "7469976997",
    companyName: "SRI RAJESHWAR MEDICAL",
    name: "SRI RAJESHWAR MEDICAL",
  },
  {
    contact: "9500702368",
    companyName: "SRI RAM CORPORATION",
    name: "SRI RAM CORPORATION",
  },
  {
    contact: "9786400143",
    companyName: "SRI RAM MEDICAL",
    name: "SRI RAM MEDICAL",
  },
  {
    contact: "9600201737",
    companyName: "SRI RAM MEDICAL STORE",
    name: "SRI RAM MEDICAL STORE",
  },
  {
    contact: "9443650683",
    companyName: "SRI RAM PHARMA",
    name: "SRI RAM PHARMA",
  },
  {
    contact: "9443484107",
    companyName: "SRI RAM PHARMA",
    name: "SRI RAM PHARMA",
  },
  {
    contact: "6374191265",
    companyName: "SRI RAM PHARMA",
    name: "SRI RAM PHARMA",
  },
  {
    contact: "9944892947",
    companyName: "SRI RAM PHARMA",
    name: "SRI RAM PHARMA",
  },
  {
    contact: "9443442057",
    companyName: "SRI RAM PHARMA",
    name: "SRI RAM PHARMA",
  },
  {
    contact: "9600201737",
    companyName: "SRI RAM PHARMA",
    name: "SRI RAM PHARMA",
  },
  {
    contact: "9443442057",
    companyName: "SRI RAM PHARMA - HARUR",
    name: "SRI RAM PHARMA - HARUR",
  },
  {
    contact: "9443810009",
    companyName: "SRI RANGA MEDICALS",
    name: "SRI RANGA MEDICALS",
  },
  {
    contact: "9944992294",
    companyName: "SRI RANI PHARMA",
    name: "SRI RANI PHARMA",
  },
  {
    contact: "9865386685",
    companyName: "SRI RASI PHARMACEUTICAL DISTRIBUTORS",
    name: "SRI RASI PHARMACEUTICAL DISTRIBUTORS",
  },
  {
    contact: "9842915172",
    companyName: "SRI RATHNA PHARMA",
    name: "SRI RATHNA PHARMA",
  },
  {
    contact: "6380773430",
    companyName: "SRI RATHNA PHARMA",
    name: "SRI RATHNA PHARMA",
  },
  {
    contact: "9585530055",
    companyName: "SRI RIVETHAA PHARMA",
    name: "SRI RIVETHAA PHARMA",
  },
  {
    contact: "9840546899",
    companyName: "SRI SA MEDICALS",
    name: "SRI SA MEDICALS",
  },
  {
    contact: "9488521474",
    companyName: "SRI SAAI GIRI AGENCIES",
    name: "SRI SAAI GIRI AGENCIES",
  },
  {
    contact: "9952212814",
    companyName: "SRI SAAI PHARMA",
    name: "SRI SAAI PHARMA",
  },
  {
    contact: "9952212814",
    companyName: "SRI SAAI PHARMA",
    name: "SRI SAAI PHARMA",
  },
  {
    contact: "7200484894",
    companyName: "SRI SAI RAM PHARMA",
    name: "SRI SAI RAM PHARMA",
  },
  {
    contact: "9952402352",
    companyName: "SRI SAI RAM PHARMA",
    name: "SRI SAI RAM PHARMA",
  },
  {
    contact: "7667244487",
    companyName: "SRI SAIRAM PHARMA",
    name: "SRI SAIRAM PHARMA",
  },
  {
    contact: "9566715806 / 7200484894",
    companyName: "SRI SAIRAM PHARMA DISTRIBUTORS",
    name: "SRI SAIRAM PHARMA DISTRIBUTORS",
  },
  {
    contact: "8003383300",
    companyName: "SRI SAKTHI PHARMA",
    name: "SRI SAKTHI PHARMA",
  },
  {
    contact: "6383732065",
    companyName: "SRI SALEM PHARMA DISTRIBUTORS",
    name: "SRI SALEM PHARMA DISTRIBUTORS",
  },
  {
    contact: "8778995793",
    companyName: "SRI SALEM PHARMA DISTRIBUTORS",
    name: "SRI SALEM PHARMA DISTRIBUTORS",
  },
  {
    contact: "9362674934",
    companyName: "SRI SAMI PHARMA",
    name: "SRI SAMI PHARMA",
  },
  {
    contact: "9842471707",
    companyName: "SRI SAMUTHRA AGENCY ",
    name: "SRI SAMUTHRA AGENCY ",
  },
  {
    contact: "9566419164",
    companyName: "SRI SARASWATHI AGENCY",
    name: "SRI SARASWATHI AGENCY",
  },
  {
    contact: "9944033308",
    companyName: "SRI SARAVANA PHARMA",
    name: "SRI SARAVANA PHARMA",
  },
  {
    contact: "9944033308",
    companyName: "SRI SARAVANA PHARMA",
    name: "SRI SARAVANA PHARMA",
  },
  {
    contact: "9944622029",
    companyName: "SRI SATHGURU PHARMA",
    name: "SRI SATHGURU PHARMA",
  },
  {
    contact: "9789782025",
    companyName: "SRI SENTHIL ANDAVAR MEDICAL AGENCIES",
    name: "SRI SENTHIL ANDAVAR MEDICAL AGENCIES",
  },
  {
    contact: "9500449588",
    companyName: "SRI SHANMUNDI PHARMA",
    name: "SRI SHANMUNDI PHARMA",
  },
  {
    contact: "9943766337",
    companyName: "SRI SHENBAGA VINAYAGAR AGENCIES",
    name: "SRI SHENBAGA VINAYAGAR AGENCIES",
  },
  {
    contact: "9442492694",
    companyName: "SRI SIVA PHARMA",
    name: "SRI SIVA PHARMA",
  },
  {
    contact: "9443485027",
    companyName: "SRI SIVAKUMAR PHARMA",
    name: "SRI SIVAKUMAR PHARMA",
  },
  {
    contact: "7871188977",
    companyName: "SRI SIVASAKTHI PHARMA",
    name: "SRI SIVASAKTHI PHARMA",
  },
  {
    contact: "9626108917",
    companyName: "SRI SRINIVASA MEDICALS",
    name: "SRI SRINIVASA MEDICALS",
  },
  {
    contact: "7200668912",
    companyName: "SRI SRINIVASA MEDICALS - KOOVATHUR",
    name: "SRI SRINIVASA MEDICALS - KOOVATHUR",
  },
  {
    contact: "9488431303",
    companyName: "SRI SUBALAKSHMI MEDICALS",
    name: "SRI SUBALAKSHMI MEDICALS",
  },
  {
    contact: "6383084954",
    companyName: "SRI SUBALAXMI MEDICALS",
    name: "SRI SUBALAXMI MEDICALS",
  },
  {
    contact: "9443512594",
    companyName: "SRI SUBULAXMI MEDICALS",
    name: "SRI SUBULAXMI MEDICALS",
  },
  {
    contact: "9486656660",
    companyName: "SRI SUN PHARMA - ERODE",
    name: "SRI SUN PHARMA - ERODE",
  },
  {
    contact: "9940300890",
    companyName: "SRI SUSIL ENTERPRISES",
    name: "SRI SUSIL ENTERPRISES",
  },
  {
    contact: "9486267199",
    companyName: "SRI SWASTIK AGENCIES",
    name: "SRI SWASTIK AGENCIES",
  },
  {
    contact: "9962626286",
    companyName: "SRI THANIGAI PHARMACEUTICALS",
    name: "SRI THANIGAI PHARMACEUTICALS",
  },
  {
    contact: "9962626286 /9094806135",
    companyName: "SRI THANIGAI PHARMACEUTICALS",
    name: "SRI THANIGAI PHARMACEUTICALS",
  },
  {
    contact: "9488431305",
    companyName: "SRI THIRUMALAI AGENCIES",
    name: "SRI THIRUMALAI AGENCIES",
  },
  {
    contact: "9488431305",
    companyName: "SRI THIRUMALAI AGENCIES..",
    name: "SRI THIRUMALAI AGENCIES..",
  },
  {
    contact: "9841322235/98",
    companyName: "SRI TULSI PHARMA DISTRIBUTOR",
    name: "SRI TULSI PHARMA DISTRIBUTOR",
  },
  {
    contact: "9841260112",
    companyName: "SRI TULSI PHARMA DISTRIBUTORS",
    name: "SRI TULSI PHARMA DISTRIBUTORS",
  },
  {
    contact: "9841721868",
    companyName: "SRI VAISHIYA PHARMA",
    name: "SRI VAISHIYA PHARMA",
  },
  {
    contact: "9841721868",
    companyName: "SRI VAISHYA PHARMA & SURGICALS",
    name: "SRI VAISHYA PHARMA & SURGICALS",
  },
  {
    contact: "9487873191",
    companyName: "SRI VALLI PHARMA",
    name: "SRI VALLI PHARMA",
  },
  {
    contact: "9445358909",
    companyName: "SRI VARI MEDICAL DISTRIBUTORS",
    name: "SRI VARI MEDICAL DISTRIBUTORS",
  },
  {
    contact: "9677167543",
    companyName: "SRI VARI MEDICAL SURGICAL",
    name: "SRI VARI MEDICAL SURGICAL",
  },
  {
    contact: "9655130278",
    companyName: "SRI VARI PHARMA",
    name: "SRI VARI PHARMA",
  },
  {
    contact: "9894447224",
    companyName: "SRI VARI PHARMA",
    name: "SRI VARI PHARMA",
  },
  {
    contact: "9965308035",
    companyName: "SRI VARI PHARMA",
    name: "SRI VARI PHARMA",
  },
  {
    contact: "9791020678",
    companyName: "SRI VARI PHARMA DISTRIBUTOR",
    name: "SRI VARI PHARMA DISTRIBUTOR",
  },
  {
    contact: "9500245930",
    companyName: "SRI VENKATESHWARA PHARMA",
    name: "SRI VENKATESHWARA PHARMA",
  },
  {
    contact: "9043816685",
    companyName: "SRI VENKATESHWARA PHARMA",
    name: "SRI VENKATESHWARA PHARMA",
  },
  {
    contact: "9443149681",
    companyName: "SRI VENKATESWARA PHARMA",
    name: "SRI VENKATESWARA PHARMA",
  },
  {
    contact: "9944353237",
    companyName: "SRI VENKESWARA DRUG HOUSE",
    name: "SRI VENKESWARA DRUG HOUSE",
  },
  {
    contact: "9842323676",
    companyName: "SRI VETRI PHARMA",
    name: "SRI VETRI PHARMA",
  },
  {
    contact: "9445230075",
    companyName: "SRI VETRI PHARMA",
    name: "SRI VETRI PHARMA",
  },
  {
    contact: "9842223121",
    companyName: "SRI VIGENSHWAR PHARMA",
    name: "SRI VIGENSHWAR PHARMA",
  },
  {
    contact: "9994554555",
    companyName: "SRI VIGNESH MEDICAL AGENCIS",
    name: "SRI VIGNESH MEDICAL AGENCIS",
  },
  {
    contact: "9043792382",
    companyName: "SRI VIGNESH PHARMA",
    name: "SRI VIGNESH PHARMA",
  },
  {
    contact: "9842223121",
    companyName: "SRI VIGNESHWAR PHARMACEUTICAL DISTRIBUTO",
    name: "SRI VIGNESHWAR PHARMACEUTICAL DISTRIBUTO",
  },
  {
    contact: "9566125477",
    companyName: "SRI VIGNESHWARA PHARMACEUTICALS",
    name: "SRI VIGNESHWARA PHARMACEUTICALS",
  },
  {
    contact: "9840277376",
    companyName: "SRI VIJAY GANAPATHY ENTERPRISES",
    name: "SRI VIJAY GANAPATHY ENTERPRISES",
  },
  {
    contact: "9842319735",
    companyName: "SRI VINAYAGA PHARMA",
    name: "SRI VINAYAGA PHARMA",
  },
  {
    contact: "9994910555",
    companyName: "SRI VINAYAKA PHARMA",
    name: "SRI VINAYAKA PHARMA",
  },
  {
    contact: "9842032918",
    companyName: "SRIE SARASWATHI MEDICAL AGENCIES",
    name: "SRIE SARASWATHI MEDICAL AGENCIES",
  },
  {
    contact: "9790860289",
    companyName: "SRINIDHI PHARMA DISTRIBUTORS",
    name: "SRINIDHI PHARMA DISTRIBUTORS",
  },
  {
    contact: "9942222992",
    companyName: "SRINIVASA AGENCY",
    name: "SRINIVASA AGENCY",
  },
  {
    contact: "9942222992",
    companyName: "SRINIVASA AGENCY",
    name: "SRINIVASA AGENCY",
  },
  {
    contact: "7093907762",
    companyName: "SRINIVASA AGENCY",
    name: "SRINIVASA AGENCY",
  },
  {
    contact: "9486843389",
    companyName: "SRINIVASA PHARMA",
    name: "SRINIVASA PHARMA",
  },
  { contact: "9865412982", companyName: "SRM PHARMA", name: "SRM PHARMA" },
  {
    contact: "8072547140",
    companyName: "STANDARD PHARMACY",
    name: "STANDARD PHARMACY",
  },
  { contact: "8825482481", companyName: "STAR PHARMA", name: "STAR PHARMA" },
  { contact: "8825482481", companyName: "STAR PHARMA", name: "STAR PHARMA" },
  { contact: "9944315866", companyName: "STAR PHARMA", name: "STAR PHARMA" },
  {
    contact: "9443448708",
    companyName: "STEVE & MARKS PHARMACEUTICALS",
    name: "STEVE & MARKS PHARMACEUTICALS",
  },
  {
    contact: "9449448708",
    companyName: "STEVE&MARK PHARMACEUTICALS",
    name: "STEVE&MARK PHARMACEUTICALS",
  },
  {
    contact: "9842255261",
    companyName: "SUBBU AGENCIES",
    name: "SUBBU AGENCIES",
  },
  {
    contact: "9865761710",
    companyName: "SUCCESS PHARMA",
    name: "SUCCESS PHARMA",
  },
  {
    contact: "9443701983",
    companyName: "SUMANGALI PHARMACETICALS",
    name: "SUMANGALI PHARMACETICALS",
  },
  {
    contact: "9842102526",
    companyName: "SUN MEDICAL & SURGICALS",
    name: "SUN MEDICAL & SURGICALS",
  },
  { contact: "9842102526", companyName: "SUN PHARMA", name: "SUN PHARMA" },
  { contact: "9894322766", companyName: "SUN SUN DRUG", name: "SUN SUN DRUG" },
  {
    contact: "9842713819",
    companyName: "SUNDARAM AGENCIES",
    name: "SUNDARAM AGENCIES",
  },
  {
    contact: "9894050609",
    companyName: "SURABHI AGENCIES",
    name: "SURABHI AGENCIES",
  },
  {
    contact: "9159131836",
    companyName: "SURESH PHARMA",
    name: "SURESH PHARMA",
  },
  {
    contact: "9842304776",
    companyName: "SURGICAL POINT",
    name: "SURGICAL POINT",
  },
  {
    contact: "9842411178",
    companyName: "SURGIDENT PHARMA",
    name: "SURGIDENT PHARMA",
  },
  {
    contact: "9894880366",
    companyName: "SURYA ENTERPRISES",
    name: "SURYA ENTERPRISES",
  },
  { contact: "9789210907", companyName: "SVR PHARMA", name: "SVR PHARMA" },
  { contact: "9789210907", companyName: "SVR PHARMA", name: "SVR PHARMA" },
  {
    contact: "7904100467",
    companyName: "SWASTIK AGENCIES",
    name: "SWASTIK AGENCIES",
  },
  {
    contact: "8754954406",
    companyName: "SWASTIK PHARMA",
    name: "SWASTIK PHARMA",
  },
  {
    contact: "9965560087",
    companyName: "SWATHI ENTERPRISES",
    name: "SWATHI ENTERPRISES",
  },
  {
    contact: "9965560087",
    companyName: "SWATHI ENTRERPRIES",
    name: "SWATHI ENTRERPRIES",
  },
  { contact: "9600043833", companyName: "SWISS PHARMA", name: "SWISS PHARMA" },
  { contact: "9944331735", companyName: "TAAG PHARMA", name: "TAAG PHARMA" },
  { contact: "9842582197", companyName: "TAJ PHARMA", name: "TAJ PHARMA" },
  {
    contact: "9787730608",
    companyName: "TAMILNADU MEDICAL AGENCIES",
    name: "TAMILNADU MEDICAL AGENCIES",
  },
  {
    contact: "9500655572 / 9994455574",
    companyName: "THANGAM DRUGS",
    name: "THANGAM DRUGS",
  },
  {
    contact: "9500655572",
    companyName: "THANGAM DRUGS - ERODE",
    name: "THANGAM DRUGS - ERODE",
  },
  {
    contact: "9962100182",
    companyName: "THANGAM MEDICAL AND DISTRIBUTORS",
    name: "THANGAM MEDICAL AND DISTRIBUTORS",
  },
  {
    contact: "9094806135",
    companyName: "THANIGAI PHARMA",
    name: "THANIGAI PHARMA",
  },
  {
    contact: "9443452145",
    companyName: "THANU &COMPANY",
    name: "THANU &COMPANY",
  },
  {
    contact: "9865412982",
    companyName: "THE S.R.M PHARMA SURGICAL",
    name: "THE S.R.M PHARMA SURGICAL",
  },
  {
    contact: "9842473631",
    companyName: "THEIVA MEDICAL AGENCIES",
    name: "THEIVA MEDICAL AGENCIES",
  },
  {
    contact: "9842945637",
    companyName: "THIRUMALAI AGENCIES",
    name: "THIRUMALAI AGENCIES",
  },
  {
    contact: "9442315896",
    companyName: "THIRUPATHI AGENCIES",
    name: "THIRUPATHI AGENCIES",
  },
  {
    contact: "9976974024",
    companyName: "THIRUPATHI AGENCIES",
    name: "THIRUPATHI AGENCIES",
  },
  {
    contact: "9943725151",
    companyName: "THIYAGARAJA TRADER",
    name: "THIYAGARAJA TRADER",
  },
  {
    contact: "9551285557",
    companyName: "TIRUMALA PHARMA DISTRIBUTORS",
    name: "TIRUMALA PHARMA DISTRIBUTORS",
  },
  {
    contact: "9551285557",
    companyName: "TIRUMALA PHARMA DISTRIBUTORS",
    name: "TIRUMALA PHARMA DISTRIBUTORS",
  },
  {
    contact: "9750630222",
    companyName: "TIRUPATHI PHARMA",
    name: "TIRUPATHI PHARMA",
  },
  {
    contact: "9994404045",
    companyName: "TIRUPATHY PHARMA",
    name: "TIRUPATHY PHARMA",
  },
  {
    contact: "9443449733",
    companyName: "TRINITY MEDICAL AGENCIES",
    name: "TRINITY MEDICAL AGENCIES",
  },
  {
    contact: "9655424218",
    companyName: "TRIVY HEALTH CARE",
    name: "TRIVY HEALTH CARE",
  },
  {
    contact: "8973744595",
    companyName: "UDAYAM PHARMA",
    name: "UDAYAM PHARMA",
  },
  {
    contact: "9486442889",
    companyName: "UDHAYAM AGENCIES",
    name: "UDHAYAM AGENCIES",
  },
  {
    contact: "9944354632",
    companyName: "UMAIYAL AGENCIES",
    name: "UMAIYAL AGENCIES",
  },
  { contact: "9443480440", companyName: "UNION PHARMA", name: "UNION PHARMA" },
  {
    contact: "9443287636",
    companyName: "UNITED PHARMA",
    name: "UNITED PHARMA",
  },
  { contact: "9940998388", companyName: "V V PHARMA", name: "V V PHARMA" },
  { contact: "9940998388", companyName: "V V PHARMA", name: "V V PHARMA" },
  { contact: "9443428465", companyName: "V.K.R PHARMA", name: "V.K.R PHARMA" },
  {
    contact: "9500142112",
    companyName: "VAIBHAV PHARMA DISTRIBUTORS",
    name: "VAIBHAV PHARMA DISTRIBUTORS",
  },
  {
    contact: "9443476452",
    companyName: "VAIGAI PHARMA",
    name: "VAIGAI PHARMA",
  },
  {
    contact: "9865197467",
    companyName: "VAIRAM PHARMA",
    name: "VAIRAM PHARMA",
  },
  {
    contact: "8489925883",
    companyName: "VAISANVI SURGICALS",
    name: "VAISANVI SURGICALS",
  },
  {
    contact: "8608215572",
    companyName: "VAISHNAVI PHARMA",
    name: "VAISHNAVI PHARMA",
  },
  {
    contact: "9894769666",
    companyName: "VALLIAMMAI AGENCIES",
    name: "VALLIAMMAI AGENCIES",
  },
  {
    contact: "9952734311",
    companyName: "VANI ENTERPRISES",
    name: "VANI ENTERPRISES",
  },
  {
    contact: "9940457022",
    companyName: "VANI ENTERPRISES",
    name: "VANI ENTERPRISES",
  },
  {
    contact: "9894868123",
    companyName: "VASAN MEDICAL AGENCIES",
    name: "VASAN MEDICAL AGENCIES",
  },
  {
    contact: "9894868123",
    companyName: "VASAN MEDICAL AGENCIES",
    name: "VASAN MEDICAL AGENCIES",
  },
  {
    contact: "9443488560",
    companyName: "VASANTHA AGENCIES",
    name: "VASANTHA AGENCIES",
  },
  {
    contact: "9443891652 / 7708699429",
    companyName: "VASANTHA PHARMA",
    name: "VASANTHA PHARMA",
  },
  {
    contact: "9659383940",
    companyName: "VASANTHA PHARMA AGENCIES",
    name: "VASANTHA PHARMA AGENCIES",
  },
  {
    contact: "9865073829",
    companyName: "VASANTHAM PHARMACETICALS",
    name: "VASANTHAM PHARMACETICALS",
  },
  { contact: "9514969988", companyName: "VE. S PHARMA", name: "VE. S PHARMA" },
  {
    contact: "8056440736",
    companyName: "VEDHA MEDICARE",
    name: "VEDHA MEDICARE",
  },
  { contact: "8526849771", companyName: "VEL PHARMA", name: "VEL PHARMA" },
  {
    contact: "9944484278",
    companyName: "VELLORE PHARMACETICALS",
    name: "VELLORE PHARMACETICALS",
  },
  {
    contact: "8778870648",
    companyName: "VENKATESHWARA PHARMA",
    name: "VENKATESHWARA PHARMA",
  },
  {
    contact: "9941235123",
    companyName: "VENMAYIL MEDICAL AGENCIES",
    name: "VENMAYIL MEDICAL AGENCIES",
  },
  {
    contact: "8122553757",
    companyName: "VENNBA AGENCIES",
    name: "VENNBA AGENCIES",
  },
  { contact: "9842866873", companyName: "VENUS AGENCY", name: "VENUS AGENCY" },
  { contact: "9840191274", companyName: "VENUS AGENCY", name: "VENUS AGENCY" },
  {
    contact: "9842422532",
    companyName: "VENUS CORPORATION",
    name: "VENUS CORPORATION",
  },
  {
    contact: "9842784028",
    companyName: "VENUS MEDICAL AGENCY",
    name: "VENUS MEDICAL AGENCY",
  },
  { contact: "9865866510", companyName: "VENUS PHARMA", name: "VENUS PHARMA" },
  { contact: "9042453343", companyName: "VERTI PHARMA", name: "VERTI PHARMA" },
  {
    contact: "9943572769",
    companyName: "VIBJAR PHARMA",
    name: "VIBJAR PHARMA",
  },
  {
    contact: "9842223121",
    companyName: "VIGNESWAR PHARMACEUTICALS",
    name: "VIGNESWAR PHARMACEUTICALS",
  },
  {
    contact: "9003741176",
    companyName: "VIJAY MEDICAL AGENCY",
    name: "VIJAY MEDICAL AGENCY",
  },
  {
    contact: "9443054383",
    companyName: "VIJAY PHARMA AND SURGICALS",
    name: "VIJAY PHARMA AND SURGICALS",
  },
  {
    contact: "7845777565",
    companyName: "VIJAYA PHARMACEUTICALS",
    name: "VIJAYA PHARMACEUTICALS",
  },
  {
    contact: "9843643765",
    companyName: "VIJAYABHARATHI PHARMA",
    name: "VIJAYABHARATHI PHARMA",
  },
  {
    contact: "9842503624",
    companyName: "VIKRAM MEDICAL",
    name: "VIKRAM MEDICAL",
  },
  {
    contact: "9488345822",
    companyName: "VILVAM PHARMA",
    name: "VILVAM PHARMA",
  },
  {
    contact: "9443279424",
    companyName: "VIMAL MEDICAL AGENCIES",
    name: "VIMAL MEDICAL AGENCIES",
  },
  {
    contact: "9443279424",
    companyName: "VIMAL MEDICAL AGENCIES",
    name: "VIMAL MEDICAL AGENCIES",
  },
  { contact: "8124544744", companyName: "VIN PHARMA", name: "VIN PHARMA" },
  {
    contact: "9865131111",
    companyName: "VINAYAGA MEDICAL AGENCY",
    name: "VINAYAGA MEDICAL AGENCY",
  },
  {
    contact: "9965534652",
    companyName: "VINAYAKA PHARMA",
    name: "VINAYAKA PHARMA",
  },
  { contact: "9444148963", companyName: "VIPUL PHARMA", name: "VIPUL PHARMA" },
  {
    contact: "9047457278",
    companyName: "VIRUTCHA AGENCIES",
    name: "VIRUTCHA AGENCIES",
  },
  {
    contact: "9944289316",
    companyName: "VIRUTHAI PHARMA",
    name: "VIRUTHAI PHARMA",
  },
  {
    contact: "9840857305",
    companyName: "VISHALI AGENCIES",
    name: "VISHALI AGENCIES",
  },
  {
    contact: "9965640879",
    companyName: "VISHNU MEDICAL AGENCY",
    name: "VISHNU MEDICAL AGENCY",
  },
  {
    contact: "9790120697",
    companyName: "VISHNU PHARMA",
    name: "VISHNU PHARMA",
  },
  {
    contact: "9843753619",
    companyName: "VIVEKA PHARMA",
    name: "VIVEKA PHARMA",
  },
  { contact: "9486571648", companyName: "VIZAG PHARMA", name: "VIZAG PHARMA" },
  {
    contact: "9600008608",
    companyName: "VM PHARMA DISTRIBUTORS",
    name: "VM PHARMA DISTRIBUTORS",
  },
  {
    contact: "9655118608",
    companyName: "VM PHARMA DISTRIBUTORS",
    name: "VM PHARMA DISTRIBUTORS",
  },
  { contact: "9444713974", companyName: "VSR PHARMA", name: "VSR PHARMA" },
  {
    contact: "9443322479",
    companyName: "WAZITH MEDICAL CORPORATION",
    name: "WAZITH MEDICAL CORPORATION",
  },
  {
    contact: "9443322479",
    companyName: "WAZITH MEDICAL CORPORATION",
    name: "WAZITH MEDICAL CORPORATION",
  },
  {
    contact: "9159153939",
    companyName: "WELL CARE PHARMA",
    name: "WELL CARE PHARMA",
  },
  {
    contact: "6379697844",
    companyName: "WELNESS PHARMA",
    name: "WELNESS PHARMA",
  },
  { contact: "9894111007", companyName: "WIN PHARMA", name: "WIN PHARMA" },
  {
    contact: "9788024175",
    companyName: "WINTECH PHARMA",
    name: "WINTECH PHARMA",
  },
  {
    contact: "9443513921",
    companyName: "YASOTHA PHARMACEUTICALS",
    name: "YASOTHA PHARMACEUTICALS",
  },
  { contact: "9994456494", companyName: "YOUNG PHARMA", name: "YOUNG PHARMA" },
  { contact: "9843005004", companyName: "YUNG PHARMA", name: "YUNG PHARMA" },
  {
    contact: "9843855088",
    companyName: "YUVANA ENTERPRISES",
    name: "YUVANA ENTERPRISES",
  },
  {
    contact: "9597848341",
    companyName: "YUVANA ENTERPRISES",
    name: "YUVANA ENTERPRISES",
  },
  {
    contact: "9791233747",
    companyName: "YUVANAA ENTERPRISES",
    name: "YUVANAA ENTERPRISES",
  },
  { contact: "9944116941", companyName: "Z M PHARMA", name: "Z M PHARMA" },
  { contact: "9944116941", companyName: "Z M PHARMA", name: "Z M PHARMA" },
  {
    contact: "9443519790",
    companyName: "ZYCARE PHARMA",
    name: "ZYCARE PHARMA",
  },
];
